//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsAggregatePluginRequest.h>
#import <EsThriftUtil.h>

@implementation EsAggregatePluginRequest

@synthesize pluginRequestArray = pluginRequestArray_;

- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.messageType = EsMessageType_AggregatePluginRequest;
		self.pluginRequestArray = [NSMutableArray array];
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
	ThriftAggregatePluginRequest* t = (ThriftAggregatePluginRequest*) thriftObject;
	if ([t pluginRequestArrayIsSet] && t.pluginRequestArray != nil) {
		self.pluginRequestArray = [[[NSMutableArray alloc] init] autorelease];
		for (ThriftRequestDetails* _tValVar_0 in t.pluginRequestArray) {
			EsRequestDetails* _listDestVar_0;
			_listDestVar_0 = [[[EsRequestDetails alloc] initWithThriftObject:_tValVar_0] autorelease];
			[self.pluginRequestArray addObject: _listDestVar_0];
		}
	}
}

- (ThriftAggregatePluginRequest*) toThrift {
	ThriftAggregatePluginRequest* _t = [[[ThriftAggregatePluginRequest alloc] init] autorelease];;
	if (pluginRequestArray_set_ && pluginRequestArray_ != nil) {
		NSMutableArray* _pluginRequestArray;
		_pluginRequestArray = [[[NSMutableArray alloc] init] autorelease];
		for (EsRequestDetails* _tValVar_0 in self.pluginRequestArray) {
			ThriftRequestDetails* _listDestVar_0;
			_listDestVar_0 = [_tValVar_0 toThrift];
			[_pluginRequestArray addObject: _listDestVar_0];
		}
		_t.pluginRequestArray = _pluginRequestArray;
	}
	return _t;
}

- (id) newThrift {
	return [[ThriftAggregatePluginRequest alloc] init];
}

- (void) setPluginRequestArray: (NSMutableArray*) pluginRequestArray {
	[pluginRequestArray_ release];
	pluginRequestArray_ = [pluginRequestArray retain];
	pluginRequestArray_set_ = true;
}

- (void) dealloc {
	self.pluginRequestArray = nil;
	[super dealloc];
}

@end
