//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsConnectionResponse.h>
#import <EsThriftUtil.h>

@implementation EsConnectionResponse

@synthesize successful = successful_;
@synthesize hashId = hashId_;
@synthesize error = error_;
@synthesize protocolConfiguration = protocolConfiguration_;
@synthesize serverVersion = serverVersion_;

- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.messageType = EsMessageType_ConnectionResponse;
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
	ThriftConnectionResponse* t = (ThriftConnectionResponse*) thriftObject;
	if ([t successfulIsSet]) {
		self.successful = t.successful;
	}
	if ([t hashIdIsSet]) {
		self.hashId = t.hashId;
	}
	if ([t errorIsSet]) {
		self.error = t.error;
	}
	if ([t protocolConfigurationIsSet] && t.protocolConfiguration != nil) {
		self.protocolConfiguration = [[[EsProtocolConfiguration alloc] initWithThriftObject:t.protocolConfiguration] autorelease];
	}
	if ([t serverVersionIsSet] && t.serverVersion != nil) {
		self.serverVersion = t.serverVersion;
	}
}

- (ThriftConnectionResponse*) toThrift {
	ThriftConnectionResponse* _t = [[[ThriftConnectionResponse alloc] init] autorelease];;
	if (successful_set_) {
		BOOL _successful;
		_successful = self.successful;
		_t.successful = _successful;
	}
	if (hashId_set_) {
		int32_t _hashId;
		_hashId = self.hashId;
		_t.hashId = _hashId;
	}
	if (error_set_) {
		int _error;
		_error = self.error;
		_t.error = _error;
	}
	if (protocolConfiguration_set_ && protocolConfiguration_ != nil) {
		ThriftProtocolConfiguration* _protocolConfiguration;
		_protocolConfiguration = [self.protocolConfiguration toThrift];
		_t.protocolConfiguration = _protocolConfiguration;
	}
	if (serverVersion_set_ && serverVersion_ != nil) {
		NSString* _serverVersion;
		_serverVersion = self.serverVersion;
		_t.serverVersion = _serverVersion;
	}
	return _t;
}

- (id) newThrift {
	return [[ThriftConnectionResponse alloc] init];
}

- (void) setSuccessful: (BOOL) successful {
	successful_ = successful;
	successful_set_ = true;
}

- (void) setHashId: (int32_t) hashId {
	hashId_ = hashId;
	hashId_set_ = true;
}

- (void) setError: (int) error {
	error_ = error;
	error_set_ = true;
}

- (void) setProtocolConfiguration: (EsProtocolConfiguration*) protocolConfiguration {
	[protocolConfiguration_ release];
	protocolConfiguration_ = [protocolConfiguration retain];
	protocolConfiguration_set_ = true;
}

- (void) setServerVersion: (NSString*) serverVersion {
	[serverVersion_ release];
	serverVersion_ = [serverVersion retain];
	serverVersion_set_ = true;
}

- (void) dealloc {
	self.protocolConfiguration = nil;
	self.serverVersion = nil;
	[super dealloc];
}

@end
