//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsConnectionAttemptResponse.h>
#import <EsThriftUtil.h>

@implementation EsConnectionAttemptResponse

@synthesize successful = successful_;
@synthesize connectionId = connectionId_;
@synthesize error = error_;

- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.messageType = EsMessageType_ConnectionAttemptResponse;
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
	ThriftConnectionAttemptResponse* t = (ThriftConnectionAttemptResponse*) thriftObject;
	if ([t successfulIsSet]) {
		self.successful = t.successful;
	}
	if ([t connectionIdIsSet]) {
		self.connectionId = t.connectionId;
	}
	if ([t errorIsSet]) {
		self.error = t.error;
	}
}

- (ThriftConnectionAttemptResponse*) toThrift {
	ThriftConnectionAttemptResponse* _t = [[[ThriftConnectionAttemptResponse alloc] init] autorelease];;
	if (successful_set_) {
		BOOL _successful;
		_successful = self.successful;
		_t.successful = _successful;
	}
	if (connectionId_set_) {
		int32_t _connectionId;
		_connectionId = self.connectionId;
		_t.connectionId = _connectionId;
	}
	if (error_set_) {
		int _error;
		_error = self.error;
		_t.error = _error;
	}
	return _t;
}

- (id) newThrift {
	return [[ThriftConnectionAttemptResponse alloc] init];
}

- (void) setSuccessful: (BOOL) successful {
	successful_ = successful;
	successful_set_ = true;
}

- (void) setConnectionId: (int32_t) connectionId {
	connectionId_ = connectionId;
	connectionId_set_ = true;
}

- (void) setError: (int) error {
	error_ = error;
	error_set_ = true;
}

- (void) dealloc {
	[super dealloc];
}

@end
