//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsCrossDomainPolicyResponse.h>
#import <EsThriftUtil.h>

@implementation EsCrossDomainPolicyResponse

@synthesize customFileEnabled = customFileEnabled_;
@synthesize customFileContents = customFileContents_;
@synthesize port = port_;

- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.messageType = EsMessageType_CrossDomainResponse;
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
	ThriftCrossDomainPolicyResponse* t = (ThriftCrossDomainPolicyResponse*) thriftObject;
	if ([t customFileEnabledIsSet]) {
		self.customFileEnabled = t.customFileEnabled;
	}
	if ([t customFileContentsIsSet] && t.customFileContents != nil) {
		self.customFileContents = t.customFileContents;
	}
	if ([t portIsSet]) {
		self.port = t.port;
	}
}

- (ThriftCrossDomainPolicyResponse*) toThrift {
	ThriftCrossDomainPolicyResponse* _t = [[[ThriftCrossDomainPolicyResponse alloc] init] autorelease];;
	if (customFileEnabled_set_) {
		BOOL _customFileEnabled;
		_customFileEnabled = self.customFileEnabled;
		_t.customFileEnabled = _customFileEnabled;
	}
	if (customFileContents_set_ && customFileContents_ != nil) {
		NSString* _customFileContents;
		_customFileContents = self.customFileContents;
		_t.customFileContents = _customFileContents;
	}
	if (port_set_) {
		int32_t _port;
		_port = self.port;
		_t.port = _port;
	}
	return _t;
}

- (id) newThrift {
	return [[ThriftCrossDomainPolicyResponse alloc] init];
}

- (void) setCustomFileEnabled: (BOOL) customFileEnabled {
	customFileEnabled_ = customFileEnabled;
	customFileEnabled_set_ = true;
}

- (void) setCustomFileContents: (NSString*) customFileContents {
	[customFileContents_ release];
	customFileContents_ = [customFileContents retain];
	customFileContents_set_ = true;
}

- (void) setPort: (int32_t) port {
	port_ = port;
	port_set_ = true;
}

- (void) dealloc {
	self.customFileContents = nil;
	[super dealloc];
}

@end
