//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsDeleteRoomVariableRequest.h>
#import <EsThriftUtil.h>

@implementation EsDeleteRoomVariableRequest

@synthesize zoneId = zoneId_;
@synthesize roomId = roomId_;
@synthesize name = name_;

- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.messageType = EsMessageType_DeleteRoomVariableRequest;
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
	ThriftDeleteRoomVariableRequest* t = (ThriftDeleteRoomVariableRequest*) thriftObject;
	if ([t zoneIdIsSet]) {
		self.zoneId = t.zoneId;
	}
	if ([t roomIdIsSet]) {
		self.roomId = t.roomId;
	}
	if ([t nameIsSet] && t.name != nil) {
		self.name = t.name;
	}
}

- (ThriftDeleteRoomVariableRequest*) toThrift {
	ThriftDeleteRoomVariableRequest* _t = [[[ThriftDeleteRoomVariableRequest alloc] init] autorelease];;
	if (zoneId_set_) {
		int32_t _zoneId;
		_zoneId = self.zoneId;
		_t.zoneId = _zoneId;
	}
	if (roomId_set_) {
		int32_t _roomId;
		_roomId = self.roomId;
		_t.roomId = _roomId;
	}
	if (name_set_ && name_ != nil) {
		NSString* _name;
		_name = self.name;
		_t.name = _name;
	}
	return _t;
}

- (id) newThrift {
	return [[ThriftDeleteRoomVariableRequest alloc] init];
}

- (void) setZoneId: (int32_t) zoneId {
	zoneId_ = zoneId;
	zoneId_set_ = true;
}

- (void) setRoomId: (int32_t) roomId {
	roomId_ = roomId;
	roomId_set_ = true;
}

- (void) setName: (NSString*) name {
	[name_ release];
	name_ = [name retain];
	name_set_ = true;
}

- (void) dealloc {
	self.name = nil;
	[super dealloc];
}

@end
