//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsDHSharedModulusResponse.h>
#import <EsThriftUtil.h>

@implementation EsDHSharedModulusResponse

@synthesize number = number_;

- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.messageType = EsMessageType_DHSharedModulusResponse;
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
	ThriftDHSharedModulusResponse* t = (ThriftDHSharedModulusResponse*) thriftObject;
	if ([t numberIsSet] && t.number != nil) {
		self.number = t.number;
	}
}

- (ThriftDHSharedModulusResponse*) toThrift {
	ThriftDHSharedModulusResponse* _t = [[[ThriftDHSharedModulusResponse alloc] init] autorelease];;
	if (number_set_ && number_ != nil) {
		NSString* _number;
		_number = self.number;
		_t.number = _number;
	}
	return _t;
}

- (id) newThrift {
	return [[ThriftDHSharedModulusResponse alloc] init];
}

- (void) setNumber: (NSString*) number {
	[number_ release];
	number_ = [number retain];
	number_set_ = true;
}

- (void) dealloc {
	self.number = nil;
	[super dealloc];
}

@end
