//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsFindGamesResponse.h>
#import <EsThriftUtil.h>

@implementation EsFindGamesResponse

@synthesize games = games_;

- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.messageType = EsMessageType_FindGamesResponse;
		self.games = [NSMutableArray array];
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
	ThriftFindGamesResponse* t = (ThriftFindGamesResponse*) thriftObject;
	if ([t gamesIsSet] && t.games != nil) {
		self.games = [[[NSMutableArray alloc] init] autorelease];
		for (ThriftServerGame* _tValVar_0 in t.games) {
			EsServerGame* _listDestVar_0;
			_listDestVar_0 = [[[EsServerGame alloc] initWithThriftObject:_tValVar_0] autorelease];
			[self.games addObject: _listDestVar_0];
		}
	}
}

- (ThriftFindGamesResponse*) toThrift {
	ThriftFindGamesResponse* _t = [[[ThriftFindGamesResponse alloc] init] autorelease];;
	if (games_set_ && games_ != nil) {
		NSMutableArray* _games;
		_games = [[[NSMutableArray alloc] init] autorelease];
		for (EsServerGame* _tValVar_0 in self.games) {
			ThriftServerGame* _listDestVar_0;
			_listDestVar_0 = [_tValVar_0 toThrift];
			[_games addObject: _listDestVar_0];
		}
		_t.games = _games;
	}
	return _t;
}

- (id) newThrift {
	return [[ThriftFindGamesResponse alloc] init];
}

- (void) setGames: (NSMutableArray*) games {
	[games_ release];
	games_ = [games retain];
	games_set_ = true;
}

- (void) dealloc {
	self.games = nil;
	[super dealloc];
}

@end
