//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsFindZoneAndRoomByNameRequest.h>
#import <EsThriftUtil.h>

@implementation EsFindZoneAndRoomByNameRequest

@synthesize zoneName = zoneName_;
@synthesize roomName = roomName_;

- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.messageType = EsMessageType_FindZoneAndRoomByNameRequest;
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
	ThriftFindZoneAndRoomByNameRequest* t = (ThriftFindZoneAndRoomByNameRequest*) thriftObject;
	if ([t zoneNameIsSet] && t.zoneName != nil) {
		self.zoneName = t.zoneName;
	}
	if ([t roomNameIsSet] && t.roomName != nil) {
		self.roomName = t.roomName;
	}
}

- (ThriftFindZoneAndRoomByNameRequest*) toThrift {
	ThriftFindZoneAndRoomByNameRequest* _t = [[[ThriftFindZoneAndRoomByNameRequest alloc] init] autorelease];;
	if (zoneName_set_ && zoneName_ != nil) {
		NSString* _zoneName;
		_zoneName = self.zoneName;
		_t.zoneName = _zoneName;
	}
	if (roomName_set_ && roomName_ != nil) {
		NSString* _roomName;
		_roomName = self.roomName;
		_t.roomName = _roomName;
	}
	return _t;
}

- (id) newThrift {
	return [[ThriftFindZoneAndRoomByNameRequest alloc] init];
}

- (void) setZoneName: (NSString*) zoneName {
	[zoneName_ release];
	zoneName_ = [zoneName retain];
	zoneName_set_ = true;
}

- (void) setRoomName: (NSString*) roomName {
	[roomName_ release];
	roomName_ = [roomName retain];
	roomName_set_ = true;
}

- (void) dealloc {
	self.zoneName = nil;
	self.roomName = nil;
	[super dealloc];
}

@end
