//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsFlattenedEsObject.h>
#import <EsThriftUtil.h>

@implementation EsFlattenedEsObject

@synthesize encodedEntries = encodedEntries_;

- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.encodedEntries = [NSMutableArray array];
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
	ThriftFlattenedEsObject* t = (ThriftFlattenedEsObject*) thriftObject;
	if ([t encodedEntriesIsSet] && t.encodedEntries != nil) {
		self.encodedEntries = [[[NSMutableArray alloc] init] autorelease];
		for (NSNumber* _tValVar_0 in t.encodedEntries) {
			NSNumber* _listDestVar_0;
			_listDestVar_0 = _tValVar_0;
			[self.encodedEntries addObject: _listDestVar_0];
		}
	}
}

- (ThriftFlattenedEsObject*) toThrift {
	ThriftFlattenedEsObject* _t = [[[ThriftFlattenedEsObject alloc] init] autorelease];;
	if (encodedEntries_set_ && encodedEntries_ != nil) {
		NSMutableArray* _encodedEntries;
		_encodedEntries = [[[NSMutableArray alloc] init] autorelease];
		for (NSNumber* _tValVar_0 in self.encodedEntries) {
			NSNumber* _listDestVar_0;
			_listDestVar_0 = _tValVar_0;
			[_encodedEntries addObject: _listDestVar_0];
		}
		_t.encodedEntries = _encodedEntries;
	}
	return _t;
}

- (id) newThrift {
	return [[ThriftFlattenedEsObject alloc] init];
}

- (void) setEncodedEntries: (NSMutableArray*) encodedEntries {
	[encodedEntries_ release];
	encodedEntries_ = [encodedEntries retain];
	encodedEntries_set_ = true;
}

- (void) dealloc {
	self.encodedEntries = nil;
	[super dealloc];
}

@end
