//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsGetUserCountResponse.h>
#import <EsThriftUtil.h>

@implementation EsGetUserCountResponse

@synthesize count = count_;

- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.messageType = EsMessageType_GetUserCountResponse;
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
	ThriftGetUserCountResponse* t = (ThriftGetUserCountResponse*) thriftObject;
	if ([t countIsSet]) {
		self.count = t.count;
	}
}

- (ThriftGetUserCountResponse*) toThrift {
	ThriftGetUserCountResponse* _t = [[[ThriftGetUserCountResponse alloc] init] autorelease];;
	if (count_set_) {
		int32_t _count;
		_count = self.count;
		_t.count = _count;
	}
	return _t;
}

- (id) newThrift {
	return [[ThriftGetUserCountResponse alloc] init];
}

- (void) setCount: (int32_t) count {
	count_ = count;
	count_set_ = true;
}

- (void) dealloc {
	[super dealloc];
}

@end
