//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsGetRoomsInZoneRequest.h>
#import <EsThriftUtil.h>

@implementation EsGetRoomsInZoneRequest

@synthesize zoneId = zoneId_;
@synthesize zoneName = zoneName_;

- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.messageType = EsMessageType_GetRoomsInZoneRequest;
		self.zoneId = -1;
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
	ThriftGetRoomsInZoneRequest* t = (ThriftGetRoomsInZoneRequest*) thriftObject;
	if ([t zoneIdIsSet]) {
		self.zoneId = t.zoneId;
	}
	if ([t zoneNameIsSet] && t.zoneName != nil) {
		self.zoneName = t.zoneName;
	}
}

- (ThriftGetRoomsInZoneRequest*) toThrift {
	ThriftGetRoomsInZoneRequest* _t = [[[ThriftGetRoomsInZoneRequest alloc] init] autorelease];;
	if (zoneId_set_) {
		int32_t _zoneId;
		_zoneId = self.zoneId;
		_t.zoneId = _zoneId;
	}
	if (zoneName_set_ && zoneName_ != nil) {
		NSString* _zoneName;
		_zoneName = self.zoneName;
		_t.zoneName = _zoneName;
	}
	return _t;
}

- (id) newThrift {
	return [[ThriftGetRoomsInZoneRequest alloc] init];
}

- (void) setZoneId: (int32_t) zoneId {
	zoneId_ = zoneId;
	zoneId_set_ = true;
}

- (void) setZoneName: (NSString*) zoneName {
	[zoneName_ release];
	zoneName_ = [zoneName retain];
	zoneName_set_ = true;
}

- (void) dealloc {
	self.zoneName = nil;
	[super dealloc];
}

@end
