//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsGetServerLocalTimeResponse.h>
#import <EsThriftUtil.h>

@implementation EsGetServerLocalTimeResponse

@synthesize serverLocalTimeInMilliseconds = serverLocalTimeInMilliseconds_;

- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.messageType = EsMessageType_GetServerLocalTimeResponse;
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
	ThriftGetServerLocalTimeResponse* t = (ThriftGetServerLocalTimeResponse*) thriftObject;
	if ([t serverLocalTimeInMillisecondsIsSet]) {
		self.serverLocalTimeInMilliseconds = t.serverLocalTimeInMilliseconds;
	}
}

- (ThriftGetServerLocalTimeResponse*) toThrift {
	ThriftGetServerLocalTimeResponse* _t = [[[ThriftGetServerLocalTimeResponse alloc] init] autorelease];;
	if (serverLocalTimeInMilliseconds_set_) {
		int64_t _serverLocalTimeInMilliseconds;
		_serverLocalTimeInMilliseconds = self.serverLocalTimeInMilliseconds;
		_t.serverLocalTimeInMilliseconds = _serverLocalTimeInMilliseconds;
	}
	return _t;
}

- (id) newThrift {
	return [[ThriftGetServerLocalTimeResponse alloc] init];
}

- (void) setServerLocalTimeInMilliseconds: (int64_t) serverLocalTimeInMilliseconds {
	serverLocalTimeInMilliseconds_ = serverLocalTimeInMilliseconds;
	serverLocalTimeInMilliseconds_set_ = true;
}

- (void) dealloc {
	[super dealloc];
}

@end
