//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsGetZonesResponse.h>
#import <EsThriftUtil.h>

@implementation EsGetZonesResponse

@synthesize zones = zones_;

- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.messageType = EsMessageType_GetZonesResponse;
		self.zones = [NSMutableArray array];
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
	ThriftGetZonesResponse* t = (ThriftGetZonesResponse*) thriftObject;
	if ([t zonesIsSet] && t.zones != nil) {
		self.zones = [[[NSMutableArray alloc] init] autorelease];
		for (ThriftZoneListEntry* _tValVar_0 in t.zones) {
			EsZoneListEntry* _listDestVar_0;
			_listDestVar_0 = [[[EsZoneListEntry alloc] initWithThriftObject:_tValVar_0] autorelease];
			[self.zones addObject: _listDestVar_0];
		}
	}
}

- (ThriftGetZonesResponse*) toThrift {
	ThriftGetZonesResponse* _t = [[[ThriftGetZonesResponse alloc] init] autorelease];;
	if (zones_set_ && zones_ != nil) {
		NSMutableArray* _zones;
		_zones = [[[NSMutableArray alloc] init] autorelease];
		for (EsZoneListEntry* _tValVar_0 in self.zones) {
			ThriftZoneListEntry* _listDestVar_0;
			_listDestVar_0 = [_tValVar_0 toThrift];
			[_zones addObject: _listDestVar_0];
		}
		_t.zones = _zones;
	}
	return _t;
}

- (id) newThrift {
	return [[ThriftGetZonesResponse alloc] init];
}

- (void) setZones: (NSMutableArray*) zones {
	[zones_ release];
	zones_ = [zones retain];
	zones_set_ = true;
}

- (void) dealloc {
	self.zones = nil;
	[super dealloc];
}

@end
