//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsIdleTimeoutWarningEvent.h>
#import <EsThriftUtil.h>

@implementation EsIdleTimeoutWarningEvent


- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.messageType = EsMessageType_IdleTimeoutWarningEvent;
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
}

- (ThriftIdleTimeoutWarningEvent*) toThrift {
	ThriftIdleTimeoutWarningEvent* _t = [[[ThriftIdleTimeoutWarningEvent alloc] init] autorelease];;
	return _t;
}

- (id) newThrift {
	return [[ThriftIdleTimeoutWarningEvent alloc] init];
}

- (void) dealloc {
	[super dealloc];
}

@end
