//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsPingResponse.h>
#import <EsThriftUtil.h>

@implementation EsPingResponse

@synthesize globalResponseRequested = globalResponseRequested_;
@synthesize pingRequestId = pingRequestId_;

- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.messageType = EsMessageType_PingResponse;
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
	ThriftPingResponse* t = (ThriftPingResponse*) thriftObject;
	if ([t globalResponseRequestedIsSet]) {
		self.globalResponseRequested = t.globalResponseRequested;
	}
	if ([t pingRequestIdIsSet]) {
		self.pingRequestId = t.pingRequestId;
	}
}

- (ThriftPingResponse*) toThrift {
	ThriftPingResponse* _t = [[[ThriftPingResponse alloc] init] autorelease];;
	if (globalResponseRequested_set_) {
		BOOL _globalResponseRequested;
		_globalResponseRequested = self.globalResponseRequested;
		_t.globalResponseRequested = _globalResponseRequested;
	}
	if (pingRequestId_set_) {
		int32_t _pingRequestId;
		_pingRequestId = self.pingRequestId;
		_t.pingRequestId = _pingRequestId;
	}
	return _t;
}

- (id) newThrift {
	return [[ThriftPingResponse alloc] init];
}

- (void) setGlobalResponseRequested: (BOOL) globalResponseRequested {
	globalResponseRequested_ = globalResponseRequested;
	globalResponseRequested_set_ = true;
}

- (void) setPingRequestId: (int32_t) pingRequestId {
	pingRequestId_ = pingRequestId;
	pingRequestId_set_ = true;
}

- (void) dealloc {
	[super dealloc];
}

@end
