//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsProtocolConfiguration.h>
#import <EsThriftUtil.h>

@implementation EsProtocolConfiguration

@synthesize messageCompressionThreshold = messageCompressionThreshold_;

- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
	ThriftProtocolConfiguration* t = (ThriftProtocolConfiguration*) thriftObject;
	if ([t messageCompressionThresholdIsSet]) {
		self.messageCompressionThreshold = t.messageCompressionThreshold;
	}
}

- (ThriftProtocolConfiguration*) toThrift {
	ThriftProtocolConfiguration* _t = [[[ThriftProtocolConfiguration alloc] init] autorelease];;
	if (messageCompressionThreshold_set_) {
		int32_t _messageCompressionThreshold;
		_messageCompressionThreshold = self.messageCompressionThreshold;
		_t.messageCompressionThreshold = _messageCompressionThreshold;
	}
	return _t;
}

- (id) newThrift {
	return [[ThriftProtocolConfiguration alloc] init];
}

- (void) setMessageCompressionThreshold: (int32_t) messageCompressionThreshold {
	messageCompressionThreshold_ = messageCompressionThreshold;
	messageCompressionThreshold_set_ = true;
}

- (void) dealloc {
	[super dealloc];
}

@end
