//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsPublicMessageRequest.h>
#import <EsThriftUtil.h>

@implementation EsPublicMessageRequest

@synthesize zoneId = zoneId_;
@synthesize roomId = roomId_;
@synthesize message = message_;
@synthesize esObject = esObject_;

- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.messageType = EsMessageType_PublicMessageRequest;
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
	ThriftPublicMessageRequest* t = (ThriftPublicMessageRequest*) thriftObject;
	if ([t zoneIdIsSet]) {
		self.zoneId = t.zoneId;
	}
	if ([t roomIdIsSet]) {
		self.roomId = t.roomId;
	}
	if ([t messageIsSet] && t.message != nil) {
		self.message = t.message;
	}
	if ([t esObjectIsSet] && t.esObject != nil) {
		self.esObject = [EsThriftUtil unflattenEsObject:[[[EsFlattenedEsObject alloc] initWithThriftObject:t.esObject] autorelease]];
	}
}

- (ThriftPublicMessageRequest*) toThrift {
	ThriftPublicMessageRequest* _t = [[[ThriftPublicMessageRequest alloc] init] autorelease];;
	if (zoneId_set_) {
		int32_t _zoneId;
		_zoneId = self.zoneId;
		_t.zoneId = _zoneId;
	}
	if (roomId_set_) {
		int32_t _roomId;
		_roomId = self.roomId;
		_t.roomId = _roomId;
	}
	if (message_set_ && message_ != nil) {
		NSString* _message;
		_message = self.message;
		_t.message = _message;
	}
	if (esObject_set_ && esObject_ != nil) {
		ThriftFlattenedEsObject* _esObject;
		_esObject = [[EsThriftUtil flattenEsObject:self.esObject] toThrift];
		_t.esObject = _esObject;
	}
	return _t;
}

- (id) newThrift {
	return [[ThriftPublicMessageRequest alloc] init];
}

- (void) setZoneId: (int32_t) zoneId {
	zoneId_ = zoneId;
	zoneId_set_ = true;
}

- (void) setRoomId: (int32_t) roomId {
	roomId_ = roomId;
	roomId_set_ = true;
}

- (void) setMessage: (NSString*) message {
	[message_ release];
	message_ = [message retain];
	message_set_ = true;
}

- (void) setEsObject: (EsObject*) esObject {
	[esObject_ release];
	esObject_ = [esObject retain];
	esObject_set_ = true;
}

- (void) dealloc {
	self.message = nil;
	self.esObject = nil;
	[super dealloc];
}

@end
