//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsRemoveBuddiesResponse.h>
#import <EsThriftUtil.h>

@implementation EsRemoveBuddiesResponse

@synthesize buddiesRemoved = buddiesRemoved_;
@synthesize buddiesNotRemoved = buddiesNotRemoved_;

- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.messageType = EsMessageType_RemoveBuddiesResponse;
		self.buddiesRemoved = [NSMutableArray array];
		self.buddiesNotRemoved = [NSMutableArray array];
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
	ThriftRemoveBuddiesResponse* t = (ThriftRemoveBuddiesResponse*) thriftObject;
	if ([t buddiesRemovedIsSet] && t.buddiesRemoved != nil) {
		self.buddiesRemoved = [[[NSMutableArray alloc] init] autorelease];
		for (NSString* _tValVar_0 in t.buddiesRemoved) {
			NSString* _listDestVar_0;
			_listDestVar_0 = _tValVar_0;
			[self.buddiesRemoved addObject: _listDestVar_0];
		}
	}
	if ([t buddiesNotRemovedIsSet] && t.buddiesNotRemoved != nil) {
		self.buddiesNotRemoved = [[[NSMutableArray alloc] init] autorelease];
		for (NSString* _tValVar_0 in t.buddiesNotRemoved) {
			NSString* _listDestVar_0;
			_listDestVar_0 = _tValVar_0;
			[self.buddiesNotRemoved addObject: _listDestVar_0];
		}
	}
}

- (ThriftRemoveBuddiesResponse*) toThrift {
	ThriftRemoveBuddiesResponse* _t = [[[ThriftRemoveBuddiesResponse alloc] init] autorelease];;
	if (buddiesRemoved_set_ && buddiesRemoved_ != nil) {
		NSMutableArray* _buddiesRemoved;
		_buddiesRemoved = [[[NSMutableArray alloc] init] autorelease];
		for (NSString* _tValVar_0 in self.buddiesRemoved) {
			NSString* _listDestVar_0;
			_listDestVar_0 = _tValVar_0;
			[_buddiesRemoved addObject: _listDestVar_0];
		}
		_t.buddiesRemoved = _buddiesRemoved;
	}
	if (buddiesNotRemoved_set_ && buddiesNotRemoved_ != nil) {
		NSMutableArray* _buddiesNotRemoved;
		_buddiesNotRemoved = [[[NSMutableArray alloc] init] autorelease];
		for (NSString* _tValVar_0 in self.buddiesNotRemoved) {
			NSString* _listDestVar_0;
			_listDestVar_0 = _tValVar_0;
			[_buddiesNotRemoved addObject: _listDestVar_0];
		}
		_t.buddiesNotRemoved = _buddiesNotRemoved;
	}
	return _t;
}

- (id) newThrift {
	return [[ThriftRemoveBuddiesResponse alloc] init];
}

- (void) setBuddiesRemoved: (NSMutableArray*) buddiesRemoved {
	[buddiesRemoved_ release];
	buddiesRemoved_ = [buddiesRemoved retain];
	buddiesRemoved_set_ = true;
}

- (void) setBuddiesNotRemoved: (NSMutableArray*) buddiesNotRemoved {
	[buddiesNotRemoved_ release];
	buddiesNotRemoved_ = [buddiesNotRemoved retain];
	buddiesNotRemoved_set_ = true;
}

- (void) dealloc {
	self.buddiesRemoved = nil;
	self.buddiesNotRemoved = nil;
	[super dealloc];
}

@end
