//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsRemoveBuddiesRequest.h>
#import <EsThriftUtil.h>

@implementation EsRemoveBuddiesRequest

@synthesize buddyNames = buddyNames_;

- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.messageType = EsMessageType_RemoveBuddiesRequest;
		self.buddyNames = [NSMutableArray array];
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
	ThriftRemoveBuddiesRequest* t = (ThriftRemoveBuddiesRequest*) thriftObject;
	if ([t buddyNamesIsSet] && t.buddyNames != nil) {
		self.buddyNames = [[[NSMutableArray alloc] init] autorelease];
		for (NSString* _tValVar_0 in t.buddyNames) {
			NSString* _listDestVar_0;
			_listDestVar_0 = _tValVar_0;
			[self.buddyNames addObject: _listDestVar_0];
		}
	}
}

- (ThriftRemoveBuddiesRequest*) toThrift {
	ThriftRemoveBuddiesRequest* _t = [[[ThriftRemoveBuddiesRequest alloc] init] autorelease];;
	if (buddyNames_set_ && buddyNames_ != nil) {
		NSMutableArray* _buddyNames;
		_buddyNames = [[[NSMutableArray alloc] init] autorelease];
		for (NSString* _tValVar_0 in self.buddyNames) {
			NSString* _listDestVar_0;
			_listDestVar_0 = _tValVar_0;
			[_buddyNames addObject: _listDestVar_0];
		}
		_t.buddyNames = _buddyNames;
	}
	return _t;
}

- (id) newThrift {
	return [[ThriftRemoveBuddiesRequest alloc] init];
}

- (void) setBuddyNames: (NSMutableArray*) buddyNames {
	[buddyNames_ release];
	buddyNames_ = [buddyNames retain];
	buddyNames_set_ = true;
}

- (void) dealloc {
	self.buddyNames = nil;
	[super dealloc];
}

@end
