//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsRegisterUDPConnectionRequest.h>
#import <EsThriftUtil.h>

@implementation EsRegisterUDPConnectionRequest

@synthesize port = port_;

- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.messageType = EsMessageType_RegisterUDPConnectionRequest;
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
	ThriftRegisterUDPConnectionRequest* t = (ThriftRegisterUDPConnectionRequest*) thriftObject;
	if ([t portIsSet]) {
		self.port = t.port;
	}
}

- (ThriftRegisterUDPConnectionRequest*) toThrift {
	ThriftRegisterUDPConnectionRequest* _t = [[[ThriftRegisterUDPConnectionRequest alloc] init] autorelease];;
	if (port_set_) {
		int32_t _port;
		_port = self.port;
		_t.port = _port;
	}
	return _t;
}

- (id) newThrift {
	return [[ThriftRegisterUDPConnectionRequest alloc] init];
}

- (void) setPort: (int32_t) port {
	port_ = port;
	port_set_ = true;
}

- (void) dealloc {
	[super dealloc];
}

@end
