//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsUserUpdateEvent.h>
#import <EsThriftUtil.h>

@implementation EsUserUpdateEvent

@synthesize zoneId = zoneId_;
@synthesize roomId = roomId_;
@synthesize action = action_;
@synthesize userName = userName_;
@synthesize userVariables = userVariables_;
@synthesize sendingVideo = sendingVideo_;
@synthesize videoStreamName = videoStreamName_;

- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.messageType = EsMessageType_UserUpdateEvent;
		self.userVariables = [NSMutableArray array];
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
	ThriftUserUpdateEvent* t = (ThriftUserUpdateEvent*) thriftObject;
	if ([t zoneIdIsSet]) {
		self.zoneId = t.zoneId;
	}
	if ([t roomIdIsSet]) {
		self.roomId = t.roomId;
	}
	if ([t actionIsSet]) {
		self.action = t.action;
	}
	if ([t userNameIsSet] && t.userName != nil) {
		self.userName = t.userName;
	}
	if ([t userVariablesIsSet] && t.userVariables != nil) {
		self.userVariables = [[[NSMutableArray alloc] init] autorelease];
		for (ThriftUserVariable* _tValVar_0 in t.userVariables) {
			EsUserVariable* _listDestVar_0;
			_listDestVar_0 = [[[EsUserVariable alloc] initWithThriftObject:_tValVar_0] autorelease];
			[self.userVariables addObject: _listDestVar_0];
		}
	}
	if ([t sendingVideoIsSet]) {
		self.sendingVideo = t.sendingVideo;
	}
	if ([t videoStreamNameIsSet] && t.videoStreamName != nil) {
		self.videoStreamName = t.videoStreamName;
	}
}

- (ThriftUserUpdateEvent*) toThrift {
	ThriftUserUpdateEvent* _t = [[[ThriftUserUpdateEvent alloc] init] autorelease];;
	if (zoneId_set_) {
		int32_t _zoneId;
		_zoneId = self.zoneId;
		_t.zoneId = _zoneId;
	}
	if (roomId_set_) {
		int32_t _roomId;
		_roomId = self.roomId;
		_t.roomId = _roomId;
	}
	if (action_set_) {
		int _action;
		_action = self.action;
		_t.action = _action;
	}
	if (userName_set_ && userName_ != nil) {
		NSString* _userName;
		_userName = self.userName;
		_t.userName = _userName;
	}
	if (userVariables_set_ && userVariables_ != nil) {
		NSMutableArray* _userVariables;
		_userVariables = [[[NSMutableArray alloc] init] autorelease];
		for (EsUserVariable* _tValVar_0 in self.userVariables) {
			ThriftUserVariable* _listDestVar_0;
			_listDestVar_0 = [_tValVar_0 toThrift];
			[_userVariables addObject: _listDestVar_0];
		}
		_t.userVariables = _userVariables;
	}
	if (sendingVideo_set_) {
		BOOL _sendingVideo;
		_sendingVideo = self.sendingVideo;
		_t.sendingVideo = _sendingVideo;
	}
	if (videoStreamName_set_ && videoStreamName_ != nil) {
		NSString* _videoStreamName;
		_videoStreamName = self.videoStreamName;
		_t.videoStreamName = _videoStreamName;
	}
	return _t;
}

- (id) newThrift {
	return [[ThriftUserUpdateEvent alloc] init];
}

- (void) setZoneId: (int32_t) zoneId {
	zoneId_ = zoneId;
	zoneId_set_ = true;
}

- (void) setRoomId: (int32_t) roomId {
	roomId_ = roomId;
	roomId_set_ = true;
}

- (void) setAction: (int) action {
	action_ = action;
	action_set_ = true;
}

- (void) setUserName: (NSString*) userName {
	[userName_ release];
	userName_ = [userName retain];
	userName_set_ = true;
}

- (void) setUserVariables: (NSMutableArray*) userVariables {
	[userVariables_ release];
	userVariables_ = [userVariables retain];
	userVariables_set_ = true;
}

- (void) setSendingVideo: (BOOL) sendingVideo {
	sendingVideo_ = sendingVideo;
	sendingVideo_set_ = true;
}

- (void) setVideoStreamName: (NSString*) videoStreamName {
	[videoStreamName_ release];
	videoStreamName_ = [videoStreamName retain];
	videoStreamName_set_ = true;
}

- (void) dealloc {
	self.userName = nil;
	self.userVariables = nil;
	self.videoStreamName = nil;
	[super dealloc];
}

@end
