//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsUserEvictedFromRoomEvent.h>
#import <EsThriftUtil.h>

@implementation EsUserEvictedFromRoomEvent

@synthesize zoneId = zoneId_;
@synthesize roomId = roomId_;
@synthesize userName = userName_;
@synthesize reason = reason_;
@synthesize ban = ban_;
@synthesize duration = duration_;

- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.messageType = EsMessageType_UserEvictedFromRoomEvent;
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
	ThriftUserEvictedFromRoomEvent* t = (ThriftUserEvictedFromRoomEvent*) thriftObject;
	if ([t zoneIdIsSet]) {
		self.zoneId = t.zoneId;
	}
	if ([t roomIdIsSet]) {
		self.roomId = t.roomId;
	}
	if ([t userNameIsSet] && t.userName != nil) {
		self.userName = t.userName;
	}
	if ([t reasonIsSet] && t.reason != nil) {
		self.reason = t.reason;
	}
	if ([t banIsSet]) {
		self.ban = t.ban;
	}
	if ([t durationIsSet]) {
		self.duration = t.duration;
	}
}

- (ThriftUserEvictedFromRoomEvent*) toThrift {
	ThriftUserEvictedFromRoomEvent* _t = [[[ThriftUserEvictedFromRoomEvent alloc] init] autorelease];;
	if (zoneId_set_) {
		int32_t _zoneId;
		_zoneId = self.zoneId;
		_t.zoneId = _zoneId;
	}
	if (roomId_set_) {
		int32_t _roomId;
		_roomId = self.roomId;
		_t.roomId = _roomId;
	}
	if (userName_set_ && userName_ != nil) {
		NSString* _userName;
		_userName = self.userName;
		_t.userName = _userName;
	}
	if (reason_set_ && reason_ != nil) {
		NSString* _reason;
		_reason = self.reason;
		_t.reason = _reason;
	}
	if (ban_set_) {
		BOOL _ban;
		_ban = self.ban;
		_t.ban = _ban;
	}
	if (duration_set_) {
		int32_t _duration;
		_duration = self.duration;
		_t.duration = _duration;
	}
	return _t;
}

- (id) newThrift {
	return [[ThriftUserEvictedFromRoomEvent alloc] init];
}

- (void) setZoneId: (int32_t) zoneId {
	zoneId_ = zoneId;
	zoneId_set_ = true;
}

- (void) setRoomId: (int32_t) roomId {
	roomId_ = roomId;
	roomId_set_ = true;
}

- (void) setUserName: (NSString*) userName {
	[userName_ release];
	userName_ = [userName retain];
	userName_set_ = true;
}

- (void) setReason: (NSString*) reason {
	[reason_ release];
	reason_ = [reason retain];
	reason_set_ = true;
}

- (void) setBan: (BOOL) ban {
	ban_ = ban;
	ban_set_ = true;
}

- (void) setDuration: (int32_t) duration {
	duration_ = duration;
	duration_set_ = true;
}

- (void) dealloc {
	self.userName = nil;
	self.reason = nil;
	[super dealloc];
}

@end
