//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsValidateAdditionalLoginRequest.h>
#import <EsThriftUtil.h>

@implementation EsValidateAdditionalLoginRequest

@synthesize secret = secret_;

- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.messageType = EsMessageType_ValidateAdditionalLoginRequest;
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
	ThriftValidateAdditionalLoginRequest* t = (ThriftValidateAdditionalLoginRequest*) thriftObject;
	if ([t secretIsSet] && t.secret != nil) {
		self.secret = t.secret;
	}
}

- (ThriftValidateAdditionalLoginRequest*) toThrift {
	ThriftValidateAdditionalLoginRequest* _t = [[[ThriftValidateAdditionalLoginRequest alloc] init] autorelease];;
	if (secret_set_ && secret_ != nil) {
		NSString* _secret;
		_secret = self.secret;
		_t.secret = _secret;
	}
	return _t;
}

- (id) newThrift {
	return [[ThriftValidateAdditionalLoginRequest alloc] init];
}

- (void) setSecret: (NSString*) secret {
	[secret_ release];
	secret_ = [secret retain];
	secret_set_ = true;
}

- (void) dealloc {
	self.secret = nil;
	[super dealloc];
}

@end
