//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsZoneUpdateEvent.h>
#import <EsThriftUtil.h>

@implementation EsZoneUpdateEvent

@synthesize zoneId = zoneId_;
@synthesize action = action_;
@synthesize roomId = roomId_;
@synthesize roomCount = roomCount_;
@synthesize roomListEntry = roomListEntry_;

- (id) initWithThriftObject: (id) thriftObject {
	if ((self = [super init])) {
		self.messageType = EsMessageType_ZoneUpdateEvent;
		if (thriftObject != nil) {
			[self fromThrift: thriftObject];
		}
	}
	return self;
}

- (id) init {
	return [self initWithThriftObject: nil];
}

- (void) fromThrift: (id) thriftObject {
	ThriftZoneUpdateEvent* t = (ThriftZoneUpdateEvent*) thriftObject;
	if ([t zoneIdIsSet]) {
		self.zoneId = t.zoneId;
	}
	if ([t actionIsSet]) {
		self.action = t.action;
	}
	if ([t roomIdIsSet]) {
		self.roomId = t.roomId;
	}
	if ([t roomCountIsSet]) {
		self.roomCount = t.roomCount;
	}
	if ([t roomListEntryIsSet] && t.roomListEntry != nil) {
		self.roomListEntry = [[[EsRoomListEntry alloc] initWithThriftObject:t.roomListEntry] autorelease];
	}
}

- (ThriftZoneUpdateEvent*) toThrift {
	ThriftZoneUpdateEvent* _t = [[[ThriftZoneUpdateEvent alloc] init] autorelease];;
	if (zoneId_set_) {
		int32_t _zoneId;
		_zoneId = self.zoneId;
		_t.zoneId = _zoneId;
	}
	if (action_set_) {
		int _action;
		_action = self.action;
		_t.action = _action;
	}
	if (roomId_set_) {
		int32_t _roomId;
		_roomId = self.roomId;
		_t.roomId = _roomId;
	}
	if (roomCount_set_) {
		int32_t _roomCount;
		_roomCount = self.roomCount;
		_t.roomCount = _roomCount;
	}
	if (roomListEntry_set_ && roomListEntry_ != nil) {
		ThriftRoomListEntry* _roomListEntry;
		_roomListEntry = [self.roomListEntry toThrift];
		_t.roomListEntry = _roomListEntry;
	}
	return _t;
}

- (id) newThrift {
	return [[ThriftZoneUpdateEvent alloc] init];
}

- (void) setZoneId: (int32_t) zoneId {
	zoneId_ = zoneId;
	zoneId_set_ = true;
}

- (void) setAction: (int) action {
	action_ = action;
	action_set_ = true;
}

- (void) setRoomId: (int32_t) roomId {
	roomId_ = roomId;
	roomId_set_ = true;
}

- (void) setRoomCount: (int32_t) roomCount {
	roomCount_ = roomCount;
	roomCount_set_ = true;
}

- (void) setRoomListEntry: (EsRoomListEntry*) roomListEntry {
	[roomListEntry_ release];
	roomListEntry_ = [roomListEntry retain];
	roomListEntry_set_ = true;
}

- (void) dealloc {
	self.roomListEntry = nil;
	[super dealloc];
}

@end
