/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>

#import "ThriftRoomListEntry.h"
#import "ThriftZoneUpdateAction.h"

#import "ThriftZoneUpdateEvent.h"


@implementation ThriftZoneUpdateEventConstants
+ (void) initialize {
}
@end

@implementation ThriftZoneUpdateEvent

- (id) initWithZoneId: (int32_t) zoneId action: (int) action roomId: (int32_t) roomId roomCount: (int32_t) roomCount roomListEntry: (ThriftRoomListEntry *) roomListEntry
{
  self = [super init];
  __zoneId = zoneId;
  __zoneId_isset = YES;
  __action = action;
  __action_isset = YES;
  __roomId = roomId;
  __roomId_isset = YES;
  __roomCount = roomCount;
  __roomCount_isset = YES;
  __roomListEntry = [roomListEntry retain];
  __roomListEntry_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"zoneId"])
  {
    __zoneId = [decoder decodeInt32ForKey: @"zoneId"];
    __zoneId_isset = YES;
  }
  if ([decoder containsValueForKey: @"action"])
  {
    __action = [decoder decodeIntForKey: @"action"];
    __action_isset = YES;
  }
  if ([decoder containsValueForKey: @"roomId"])
  {
    __roomId = [decoder decodeInt32ForKey: @"roomId"];
    __roomId_isset = YES;
  }
  if ([decoder containsValueForKey: @"roomCount"])
  {
    __roomCount = [decoder decodeInt32ForKey: @"roomCount"];
    __roomCount_isset = YES;
  }
  if ([decoder containsValueForKey: @"roomListEntry"])
  {
    __roomListEntry = [[decoder decodeObjectForKey: @"roomListEntry"] retain];
    __roomListEntry_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__zoneId_isset)
  {
    [encoder encodeInt32: __zoneId forKey: @"zoneId"];
  }
  if (__action_isset)
  {
    [encoder encodeInt: __action forKey: @"action"];
  }
  if (__roomId_isset)
  {
    [encoder encodeInt32: __roomId forKey: @"roomId"];
  }
  if (__roomCount_isset)
  {
    [encoder encodeInt32: __roomCount forKey: @"roomCount"];
  }
  if (__roomListEntry_isset)
  {
    [encoder encodeObject: __roomListEntry forKey: @"roomListEntry"];
  }
}

- (void) dealloc
{
  [__roomListEntry release];
  [super dealloc];
}

- (int32_t) zoneId {
  return __zoneId;
}

- (void) setZoneId: (int32_t) zoneId {
  __zoneId = zoneId;
  __zoneId_isset = YES;
}

- (BOOL) zoneIdIsSet {
  return __zoneId_isset;
}

- (void) unsetZoneId {
  __zoneId_isset = NO;
}

- (int) action {
  return __action;
}

- (void) setAction: (int) action {
  __action = action;
  __action_isset = YES;
}

- (BOOL) actionIsSet {
  return __action_isset;
}

- (void) unsetAction {
  __action_isset = NO;
}

- (int32_t) roomId {
  return __roomId;
}

- (void) setRoomId: (int32_t) roomId {
  __roomId = roomId;
  __roomId_isset = YES;
}

- (BOOL) roomIdIsSet {
  return __roomId_isset;
}

- (void) unsetRoomId {
  __roomId_isset = NO;
}

- (int32_t) roomCount {
  return __roomCount;
}

- (void) setRoomCount: (int32_t) roomCount {
  __roomCount = roomCount;
  __roomCount_isset = YES;
}

- (BOOL) roomCountIsSet {
  return __roomCount_isset;
}

- (void) unsetRoomCount {
  __roomCount_isset = NO;
}

- (ThriftRoomListEntry *) roomListEntry {
  return [[__roomListEntry retain] autorelease];
}

- (void) setRoomListEntry: (ThriftRoomListEntry *) roomListEntry {
  [roomListEntry retain];
  [__roomListEntry release];
  __roomListEntry = roomListEntry;
  __roomListEntry_isset = YES;
}

- (BOOL) roomListEntryIsSet {
  return __roomListEntry_isset;
}

- (void) unsetRoomListEntry {
  [__roomListEntry release];
  __roomListEntry = nil;
  __roomListEntry_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setZoneId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_I32) {
          int fieldValue = [inProtocol readI32];
          [self setAction: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setRoomId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setRoomCount: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 5:
        if (fieldType == TType_STRUCT) {
          ThriftRoomListEntry *fieldValue = [[ThriftRoomListEntry alloc] init];
          [fieldValue read: inProtocol];
          [self setRoomListEntry: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"ThriftZoneUpdateEvent"];
  if (__zoneId_isset) {
    [outProtocol writeFieldBeginWithName: @"zoneId" type: TType_I32 fieldID: 1];
    [outProtocol writeI32: __zoneId];
    [outProtocol writeFieldEnd];
  }
  if (__action_isset) {
    [outProtocol writeFieldBeginWithName: @"action" type: TType_I32 fieldID: 2];
    [outProtocol writeI32: __action];
    [outProtocol writeFieldEnd];
  }
  if (__roomId_isset) {
    [outProtocol writeFieldBeginWithName: @"roomId" type: TType_I32 fieldID: 3];
    [outProtocol writeI32: __roomId];
    [outProtocol writeFieldEnd];
  }
  if (__roomCount_isset) {
    [outProtocol writeFieldBeginWithName: @"roomCount" type: TType_I32 fieldID: 4];
    [outProtocol writeI32: __roomCount];
    [outProtocol writeFieldEnd];
  }
  if (__roomListEntry_isset) {
    if (__roomListEntry != nil) {
      [outProtocol writeFieldBeginWithName: @"roomListEntry" type: TType_STRUCT fieldID: 5];
      [__roomListEntry write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"ThriftZoneUpdateEvent("];
  [ms appendString: @"zoneId:"];
  [ms appendFormat: @"%i", __zoneId];
  [ms appendString: @",action:"];
  [ms appendFormat: @"%i", __action];
  [ms appendString: @",roomId:"];
  [ms appendFormat: @"%i", __roomId];
  [ms appendString: @",roomCount:"];
  [ms appendFormat: @"%i", __roomCount];
  [ms appendString: @",roomListEntry:"];
  [ms appendFormat: @"%@", __roomListEntry];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

