/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>


#import "ThriftValidateAdditionalLoginRequest.h"


@implementation ThriftValidateAdditionalLoginRequestConstants
+ (void) initialize {
}
@end

@implementation ThriftValidateAdditionalLoginRequest

- (id) initWithSecret: (NSString *) secret
{
  self = [super init];
  __secret = [secret retain];
  __secret_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"secret"])
  {
    __secret = [[decoder decodeObjectForKey: @"secret"] retain];
    __secret_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__secret_isset)
  {
    [encoder encodeObject: __secret forKey: @"secret"];
  }
}

- (void) dealloc
{
  [__secret release];
  [super dealloc];
}

- (NSString *) secret {
  return [[__secret retain] autorelease];
}

- (void) setSecret: (NSString *) secret {
  [secret retain];
  [__secret release];
  __secret = secret;
  __secret_isset = YES;
}

- (BOOL) secretIsSet {
  return __secret_isset;
}

- (void) unsetSecret {
  [__secret release];
  __secret = nil;
  __secret_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setSecret: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"ThriftValidateAdditionalLoginRequest"];
  if (__secret_isset) {
    if (__secret != nil) {
      [outProtocol writeFieldBeginWithName: @"secret" type: TType_STRING fieldID: 1];
      [outProtocol writeString: __secret];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"ThriftValidateAdditionalLoginRequest("];
  [ms appendString: @"secret:"];
  [ms appendFormat: @"\"%@\"", __secret];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

