/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>


#import "ThriftRemoveBuddiesResponse.h"


@implementation ThriftRemoveBuddiesResponseConstants
+ (void) initialize {
}
@end

@implementation ThriftRemoveBuddiesResponse

- (id) initWithBuddiesRemoved: (NSArray *) buddiesRemoved buddiesNotRemoved: (NSArray *) buddiesNotRemoved
{
  self = [super init];
  __buddiesRemoved = [buddiesRemoved retain];
  __buddiesRemoved_isset = YES;
  __buddiesNotRemoved = [buddiesNotRemoved retain];
  __buddiesNotRemoved_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"buddiesRemoved"])
  {
    __buddiesRemoved = [[decoder decodeObjectForKey: @"buddiesRemoved"] retain];
    __buddiesRemoved_isset = YES;
  }
  if ([decoder containsValueForKey: @"buddiesNotRemoved"])
  {
    __buddiesNotRemoved = [[decoder decodeObjectForKey: @"buddiesNotRemoved"] retain];
    __buddiesNotRemoved_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__buddiesRemoved_isset)
  {
    [encoder encodeObject: __buddiesRemoved forKey: @"buddiesRemoved"];
  }
  if (__buddiesNotRemoved_isset)
  {
    [encoder encodeObject: __buddiesNotRemoved forKey: @"buddiesNotRemoved"];
  }
}

- (void) dealloc
{
  [__buddiesRemoved release];
  [__buddiesNotRemoved release];
  [super dealloc];
}

- (NSArray *) buddiesRemoved {
  return [[__buddiesRemoved retain] autorelease];
}

- (void) setBuddiesRemoved: (NSArray *) buddiesRemoved {
  [buddiesRemoved retain];
  [__buddiesRemoved release];
  __buddiesRemoved = buddiesRemoved;
  __buddiesRemoved_isset = YES;
}

- (BOOL) buddiesRemovedIsSet {
  return __buddiesRemoved_isset;
}

- (void) unsetBuddiesRemoved {
  [__buddiesRemoved release];
  __buddiesRemoved = nil;
  __buddiesRemoved_isset = NO;
}

- (NSArray *) buddiesNotRemoved {
  return [[__buddiesNotRemoved retain] autorelease];
}

- (void) setBuddiesNotRemoved: (NSArray *) buddiesNotRemoved {
  [buddiesNotRemoved retain];
  [__buddiesNotRemoved release];
  __buddiesNotRemoved = buddiesNotRemoved;
  __buddiesNotRemoved_isset = YES;
}

- (BOOL) buddiesNotRemovedIsSet {
  return __buddiesNotRemoved_isset;
}

- (void) unsetBuddiesNotRemoved {
  [__buddiesNotRemoved release];
  __buddiesNotRemoved = nil;
  __buddiesNotRemoved_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_LIST) {
          int _size0;
          [inProtocol readListBeginReturningElementType: NULL size: &_size0];
          NSMutableArray * fieldValue = [[NSMutableArray alloc] initWithCapacity: _size0];
          int _i1;
          for (_i1 = 0; _i1 < _size0; ++_i1)
          {
            NSString * _elem2 = [inProtocol readString];
            [fieldValue addObject: _elem2];
          }
          [inProtocol readListEnd];
          [self setBuddiesRemoved: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_LIST) {
          int _size3;
          [inProtocol readListBeginReturningElementType: NULL size: &_size3];
          NSMutableArray * fieldValue = [[NSMutableArray alloc] initWithCapacity: _size3];
          int _i4;
          for (_i4 = 0; _i4 < _size3; ++_i4)
          {
            NSString * _elem5 = [inProtocol readString];
            [fieldValue addObject: _elem5];
          }
          [inProtocol readListEnd];
          [self setBuddiesNotRemoved: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"ThriftRemoveBuddiesResponse"];
  if (__buddiesRemoved_isset) {
    if (__buddiesRemoved != nil) {
      [outProtocol writeFieldBeginWithName: @"buddiesRemoved" type: TType_LIST fieldID: 1];
      {
        [outProtocol writeListBeginWithElementType: TType_STRING size: [__buddiesRemoved count]];
        int i7;
        for (i7 = 0; i7 < [__buddiesRemoved count]; i7++)
        {
          [outProtocol writeString: [__buddiesRemoved objectAtIndex: i7]];
        }
        [outProtocol writeListEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  if (__buddiesNotRemoved_isset) {
    if (__buddiesNotRemoved != nil) {
      [outProtocol writeFieldBeginWithName: @"buddiesNotRemoved" type: TType_LIST fieldID: 2];
      {
        [outProtocol writeListBeginWithElementType: TType_STRING size: [__buddiesNotRemoved count]];
        int i9;
        for (i9 = 0; i9 < [__buddiesNotRemoved count]; i9++)
        {
          [outProtocol writeString: [__buddiesNotRemoved objectAtIndex: i9]];
        }
        [outProtocol writeListEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"ThriftRemoveBuddiesResponse("];
  [ms appendString: @"buddiesRemoved:"];
  [ms appendFormat: @"%@", __buddiesRemoved];
  [ms appendString: @",buddiesNotRemoved:"];
  [ms appendFormat: @"%@", __buddiesNotRemoved];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

