/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>

#import "ThriftFlattenedEsObjectRO.h"
#import "ThriftErrorType.h"

#import "ThriftGatewayKickUserRequest.h"


@implementation ThriftGatewayKickUserRequestConstants
+ (void) initialize {
}
@end

@implementation ThriftGatewayKickUserRequest

- (id) initWithClientId: (int64_t) clientId error: (int) error esObject: (ThriftFlattenedEsObjectRO *) esObject
{
  self = [super init];
  __clientId = clientId;
  __clientId_isset = YES;
  __error = error;
  __error_isset = YES;
  __esObject = [esObject retain];
  __esObject_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"clientId"])
  {
    __clientId = [decoder decodeInt64ForKey: @"clientId"];
    __clientId_isset = YES;
  }
  if ([decoder containsValueForKey: @"error"])
  {
    __error = [decoder decodeIntForKey: @"error"];
    __error_isset = YES;
  }
  if ([decoder containsValueForKey: @"esObject"])
  {
    __esObject = [[decoder decodeObjectForKey: @"esObject"] retain];
    __esObject_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__clientId_isset)
  {
    [encoder encodeInt64: __clientId forKey: @"clientId"];
  }
  if (__error_isset)
  {
    [encoder encodeInt: __error forKey: @"error"];
  }
  if (__esObject_isset)
  {
    [encoder encodeObject: __esObject forKey: @"esObject"];
  }
}

- (void) dealloc
{
  [__esObject release];
  [super dealloc];
}

- (int64_t) clientId {
  return __clientId;
}

- (void) setClientId: (int64_t) clientId {
  __clientId = clientId;
  __clientId_isset = YES;
}

- (BOOL) clientIdIsSet {
  return __clientId_isset;
}

- (void) unsetClientId {
  __clientId_isset = NO;
}

- (int) error {
  return __error;
}

- (void) setError: (int) error {
  __error = error;
  __error_isset = YES;
}

- (BOOL) errorIsSet {
  return __error_isset;
}

- (void) unsetError {
  __error_isset = NO;
}

- (ThriftFlattenedEsObjectRO *) esObject {
  return [[__esObject retain] autorelease];
}

- (void) setEsObject: (ThriftFlattenedEsObjectRO *) esObject {
  [esObject retain];
  [__esObject release];
  __esObject = esObject;
  __esObject_isset = YES;
}

- (BOOL) esObjectIsSet {
  return __esObject_isset;
}

- (void) unsetEsObject {
  [__esObject release];
  __esObject = nil;
  __esObject_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setClientId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_I32) {
          int fieldValue = [inProtocol readI32];
          [self setError: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_STRUCT) {
          ThriftFlattenedEsObjectRO *fieldValue = [[ThriftFlattenedEsObjectRO alloc] init];
          [fieldValue read: inProtocol];
          [self setEsObject: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"ThriftGatewayKickUserRequest"];
  if (__clientId_isset) {
    [outProtocol writeFieldBeginWithName: @"clientId" type: TType_I64 fieldID: 1];
    [outProtocol writeI64: __clientId];
    [outProtocol writeFieldEnd];
  }
  if (__error_isset) {
    [outProtocol writeFieldBeginWithName: @"error" type: TType_I32 fieldID: 2];
    [outProtocol writeI32: __error];
    [outProtocol writeFieldEnd];
  }
  if (__esObject_isset) {
    if (__esObject != nil) {
      [outProtocol writeFieldBeginWithName: @"esObject" type: TType_STRUCT fieldID: 3];
      [__esObject write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"ThriftGatewayKickUserRequest("];
  [ms appendString: @"clientId:"];
  [ms appendFormat: @"%qi", __clientId];
  [ms appendString: @",error:"];
  [ms appendFormat: @"%i", __error];
  [ms appendString: @",esObject:"];
  [ms appendFormat: @"%@", __esObject];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

