/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>

#import "ThriftFlattenedEsObject.h"
#import "ThriftUserVariable.h"

#import "ThriftUserListEntry.h"


@implementation ThriftUserListEntryConstants
+ (void) initialize {
}
@end

@implementation ThriftUserListEntry

- (id) initWithUserName: (NSString *) userName userVariables: (NSArray *) userVariables sendingVideo: (BOOL) sendingVideo videoStreamName: (NSString *) videoStreamName roomOperator: (BOOL) roomOperator
{
  self = [super init];
  __userName = [userName retain];
  __userName_isset = YES;
  __userVariables = [userVariables retain];
  __userVariables_isset = YES;
  __sendingVideo = sendingVideo;
  __sendingVideo_isset = YES;
  __videoStreamName = [videoStreamName retain];
  __videoStreamName_isset = YES;
  __roomOperator = roomOperator;
  __roomOperator_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"userName"])
  {
    __userName = [[decoder decodeObjectForKey: @"userName"] retain];
    __userName_isset = YES;
  }
  if ([decoder containsValueForKey: @"userVariables"])
  {
    __userVariables = [[decoder decodeObjectForKey: @"userVariables"] retain];
    __userVariables_isset = YES;
  }
  if ([decoder containsValueForKey: @"sendingVideo"])
  {
    __sendingVideo = [decoder decodeBoolForKey: @"sendingVideo"];
    __sendingVideo_isset = YES;
  }
  if ([decoder containsValueForKey: @"videoStreamName"])
  {
    __videoStreamName = [[decoder decodeObjectForKey: @"videoStreamName"] retain];
    __videoStreamName_isset = YES;
  }
  if ([decoder containsValueForKey: @"roomOperator"])
  {
    __roomOperator = [decoder decodeBoolForKey: @"roomOperator"];
    __roomOperator_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__userName_isset)
  {
    [encoder encodeObject: __userName forKey: @"userName"];
  }
  if (__userVariables_isset)
  {
    [encoder encodeObject: __userVariables forKey: @"userVariables"];
  }
  if (__sendingVideo_isset)
  {
    [encoder encodeBool: __sendingVideo forKey: @"sendingVideo"];
  }
  if (__videoStreamName_isset)
  {
    [encoder encodeObject: __videoStreamName forKey: @"videoStreamName"];
  }
  if (__roomOperator_isset)
  {
    [encoder encodeBool: __roomOperator forKey: @"roomOperator"];
  }
}

- (void) dealloc
{
  [__userName release];
  [__userVariables release];
  [__videoStreamName release];
  [super dealloc];
}

- (NSString *) userName {
  return [[__userName retain] autorelease];
}

- (void) setUserName: (NSString *) userName {
  [userName retain];
  [__userName release];
  __userName = userName;
  __userName_isset = YES;
}

- (BOOL) userNameIsSet {
  return __userName_isset;
}

- (void) unsetUserName {
  [__userName release];
  __userName = nil;
  __userName_isset = NO;
}

- (NSArray *) userVariables {
  return [[__userVariables retain] autorelease];
}

- (void) setUserVariables: (NSArray *) userVariables {
  [userVariables retain];
  [__userVariables release];
  __userVariables = userVariables;
  __userVariables_isset = YES;
}

- (BOOL) userVariablesIsSet {
  return __userVariables_isset;
}

- (void) unsetUserVariables {
  [__userVariables release];
  __userVariables = nil;
  __userVariables_isset = NO;
}

- (BOOL) sendingVideo {
  return __sendingVideo;
}

- (void) setSendingVideo: (BOOL) sendingVideo {
  __sendingVideo = sendingVideo;
  __sendingVideo_isset = YES;
}

- (BOOL) sendingVideoIsSet {
  return __sendingVideo_isset;
}

- (void) unsetSendingVideo {
  __sendingVideo_isset = NO;
}

- (NSString *) videoStreamName {
  return [[__videoStreamName retain] autorelease];
}

- (void) setVideoStreamName: (NSString *) videoStreamName {
  [videoStreamName retain];
  [__videoStreamName release];
  __videoStreamName = videoStreamName;
  __videoStreamName_isset = YES;
}

- (BOOL) videoStreamNameIsSet {
  return __videoStreamName_isset;
}

- (void) unsetVideoStreamName {
  [__videoStreamName release];
  __videoStreamName = nil;
  __videoStreamName_isset = NO;
}

- (BOOL) roomOperator {
  return __roomOperator;
}

- (void) setRoomOperator: (BOOL) roomOperator {
  __roomOperator = roomOperator;
  __roomOperator_isset = YES;
}

- (BOOL) roomOperatorIsSet {
  return __roomOperator_isset;
}

- (void) unsetRoomOperator {
  __roomOperator_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setUserName: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_LIST) {
          int _size0;
          [inProtocol readListBeginReturningElementType: NULL size: &_size0];
          NSMutableArray * fieldValue = [[NSMutableArray alloc] initWithCapacity: _size0];
          int _i1;
          for (_i1 = 0; _i1 < _size0; ++_i1)
          {
            ThriftUserVariable *_elem2 = [[ThriftUserVariable alloc] init];
            [_elem2 read: inProtocol];
            [fieldValue addObject: _elem2];
            [_elem2 release];
          }
          [inProtocol readListEnd];
          [self setUserVariables: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_BOOL) {
          BOOL fieldValue = [inProtocol readBool];
          [self setSendingVideo: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setVideoStreamName: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 5:
        if (fieldType == TType_BOOL) {
          BOOL fieldValue = [inProtocol readBool];
          [self setRoomOperator: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"ThriftUserListEntry"];
  if (__userName_isset) {
    if (__userName != nil) {
      [outProtocol writeFieldBeginWithName: @"userName" type: TType_STRING fieldID: 1];
      [outProtocol writeString: __userName];
      [outProtocol writeFieldEnd];
    }
  }
  if (__userVariables_isset) {
    if (__userVariables != nil) {
      [outProtocol writeFieldBeginWithName: @"userVariables" type: TType_LIST fieldID: 2];
      {
        [outProtocol writeListBeginWithElementType: TType_STRUCT size: [__userVariables count]];
        int i4;
        for (i4 = 0; i4 < [__userVariables count]; i4++)
        {
          [[__userVariables objectAtIndex: i4] write: outProtocol];
        }
        [outProtocol writeListEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  if (__sendingVideo_isset) {
    [outProtocol writeFieldBeginWithName: @"sendingVideo" type: TType_BOOL fieldID: 3];
    [outProtocol writeBool: __sendingVideo];
    [outProtocol writeFieldEnd];
  }
  if (__videoStreamName_isset) {
    if (__videoStreamName != nil) {
      [outProtocol writeFieldBeginWithName: @"videoStreamName" type: TType_STRING fieldID: 4];
      [outProtocol writeString: __videoStreamName];
      [outProtocol writeFieldEnd];
    }
  }
  if (__roomOperator_isset) {
    [outProtocol writeFieldBeginWithName: @"roomOperator" type: TType_BOOL fieldID: 5];
    [outProtocol writeBool: __roomOperator];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"ThriftUserListEntry("];
  [ms appendString: @"userName:"];
  [ms appendFormat: @"\"%@\"", __userName];
  [ms appendString: @",userVariables:"];
  [ms appendFormat: @"%@", __userVariables];
  [ms appendString: @",sendingVideo:"];
  [ms appendFormat: @"%i", __sendingVideo];
  [ms appendString: @",videoStreamName:"];
  [ms appendFormat: @"\"%@\"", __videoStreamName];
  [ms appendString: @",roomOperator:"];
  [ms appendFormat: @"%i", __roomOperator];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

