/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>

#import "ThriftFlattenedEsObject.h"

#import "ThriftGetUserVariablesResponse.h"


@implementation ThriftGetUserVariablesResponseConstants
+ (void) initialize {
}
@end

@implementation ThriftGetUserVariablesResponse

- (id) initWithUserName: (NSString *) userName userVariables: (NSDictionary *) userVariables
{
  self = [super init];
  __userName = [userName retain];
  __userName_isset = YES;
  __userVariables = [userVariables retain];
  __userVariables_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"userName"])
  {
    __userName = [[decoder decodeObjectForKey: @"userName"] retain];
    __userName_isset = YES;
  }
  if ([decoder containsValueForKey: @"userVariables"])
  {
    __userVariables = [[decoder decodeObjectForKey: @"userVariables"] retain];
    __userVariables_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__userName_isset)
  {
    [encoder encodeObject: __userName forKey: @"userName"];
  }
  if (__userVariables_isset)
  {
    [encoder encodeObject: __userVariables forKey: @"userVariables"];
  }
}

- (void) dealloc
{
  [__userName release];
  [__userVariables release];
  [super dealloc];
}

- (NSString *) userName {
  return [[__userName retain] autorelease];
}

- (void) setUserName: (NSString *) userName {
  [userName retain];
  [__userName release];
  __userName = userName;
  __userName_isset = YES;
}

- (BOOL) userNameIsSet {
  return __userName_isset;
}

- (void) unsetUserName {
  [__userName release];
  __userName = nil;
  __userName_isset = NO;
}

- (NSDictionary *) userVariables {
  return [[__userVariables retain] autorelease];
}

- (void) setUserVariables: (NSDictionary *) userVariables {
  [userVariables retain];
  [__userVariables release];
  __userVariables = userVariables;
  __userVariables_isset = YES;
}

- (BOOL) userVariablesIsSet {
  return __userVariables_isset;
}

- (void) unsetUserVariables {
  [__userVariables release];
  __userVariables = nil;
  __userVariables_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setUserName: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_MAP) {
          int _size0;
          [inProtocol readMapBeginReturningKeyType: NULL valueType: NULL size: &_size0];
          NSMutableDictionary * fieldValue = [[NSMutableDictionary alloc] initWithCapacity: _size0];
          int _i1;
          for (_i1 = 0; _i1 < _size0; ++_i1)
          {
            NSString * _key2 = [inProtocol readString];
            ThriftFlattenedEsObject *_val3 = [[ThriftFlattenedEsObject alloc] init];
            [_val3 read: inProtocol];
            [fieldValue setObject: _val3 forKey: _key2];
            [_val3 release];
          }
          [inProtocol readMapEnd];
          [self setUserVariables: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"ThriftGetUserVariablesResponse"];
  if (__userName_isset) {
    if (__userName != nil) {
      [outProtocol writeFieldBeginWithName: @"userName" type: TType_STRING fieldID: 1];
      [outProtocol writeString: __userName];
      [outProtocol writeFieldEnd];
    }
  }
  if (__userVariables_isset) {
    if (__userVariables != nil) {
      [outProtocol writeFieldBeginWithName: @"userVariables" type: TType_MAP fieldID: 2];
      {
        [outProtocol writeMapBeginWithKeyType: TType_STRING valueType: TType_STRUCT size: [__userVariables count]];
        NSEnumerator * _iter4 = [__userVariables keyEnumerator];
        id key5;
        while ((key5 = [_iter4 nextObject]))
        {
          [outProtocol writeString: key5];
          [[__userVariables objectForKey: key5] write: outProtocol];
        }
        [outProtocol writeMapEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"ThriftGetUserVariablesResponse("];
  [ms appendString: @"userName:"];
  [ms appendFormat: @"\"%@\"", __userName];
  [ms appendString: @",userVariables:"];
  [ms appendFormat: @"%@", __userVariables];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

