/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>


#import "ThriftProtocolConfiguration.h"


@implementation ThriftProtocolConfigurationConstants
+ (void) initialize {
}
@end

@implementation ThriftProtocolConfiguration

- (id) initWithMessageCompressionThreshold: (int32_t) messageCompressionThreshold
{
  self = [super init];
  __messageCompressionThreshold = messageCompressionThreshold;
  __messageCompressionThreshold_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"messageCompressionThreshold"])
  {
    __messageCompressionThreshold = [decoder decodeInt32ForKey: @"messageCompressionThreshold"];
    __messageCompressionThreshold_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__messageCompressionThreshold_isset)
  {
    [encoder encodeInt32: __messageCompressionThreshold forKey: @"messageCompressionThreshold"];
  }
}

- (void) dealloc
{
  [super dealloc];
}

- (int32_t) messageCompressionThreshold {
  return __messageCompressionThreshold;
}

- (void) setMessageCompressionThreshold: (int32_t) messageCompressionThreshold {
  __messageCompressionThreshold = messageCompressionThreshold;
  __messageCompressionThreshold_isset = YES;
}

- (BOOL) messageCompressionThresholdIsSet {
  return __messageCompressionThreshold_isset;
}

- (void) unsetMessageCompressionThreshold {
  __messageCompressionThreshold_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setMessageCompressionThreshold: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"ThriftProtocolConfiguration"];
  if (__messageCompressionThreshold_isset) {
    [outProtocol writeFieldBeginWithName: @"messageCompressionThreshold" type: TType_I32 fieldID: 1];
    [outProtocol writeI32: __messageCompressionThreshold];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"ThriftProtocolConfiguration("];
  [ms appendString: @"messageCompressionThreshold:"];
  [ms appendFormat: @"%i", __messageCompressionThreshold];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

