/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>


#import "ThriftDHPublicNumbersResponse.h"


@implementation ThriftDHPublicNumbersResponseConstants
+ (void) initialize {
}
@end

@implementation ThriftDHPublicNumbersResponse

- (id) initWithBaseNumber: (NSString *) baseNumber primeNumber: (NSString *) primeNumber
{
  self = [super init];
  __baseNumber = [baseNumber retain];
  __baseNumber_isset = YES;
  __primeNumber = [primeNumber retain];
  __primeNumber_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"baseNumber"])
  {
    __baseNumber = [[decoder decodeObjectForKey: @"baseNumber"] retain];
    __baseNumber_isset = YES;
  }
  if ([decoder containsValueForKey: @"primeNumber"])
  {
    __primeNumber = [[decoder decodeObjectForKey: @"primeNumber"] retain];
    __primeNumber_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__baseNumber_isset)
  {
    [encoder encodeObject: __baseNumber forKey: @"baseNumber"];
  }
  if (__primeNumber_isset)
  {
    [encoder encodeObject: __primeNumber forKey: @"primeNumber"];
  }
}

- (void) dealloc
{
  [__baseNumber release];
  [__primeNumber release];
  [super dealloc];
}

- (NSString *) baseNumber {
  return [[__baseNumber retain] autorelease];
}

- (void) setBaseNumber: (NSString *) baseNumber {
  [baseNumber retain];
  [__baseNumber release];
  __baseNumber = baseNumber;
  __baseNumber_isset = YES;
}

- (BOOL) baseNumberIsSet {
  return __baseNumber_isset;
}

- (void) unsetBaseNumber {
  [__baseNumber release];
  __baseNumber = nil;
  __baseNumber_isset = NO;
}

- (NSString *) primeNumber {
  return [[__primeNumber retain] autorelease];
}

- (void) setPrimeNumber: (NSString *) primeNumber {
  [primeNumber retain];
  [__primeNumber release];
  __primeNumber = primeNumber;
  __primeNumber_isset = YES;
}

- (BOOL) primeNumberIsSet {
  return __primeNumber_isset;
}

- (void) unsetPrimeNumber {
  [__primeNumber release];
  __primeNumber = nil;
  __primeNumber_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setBaseNumber: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setPrimeNumber: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"ThriftDHPublicNumbersResponse"];
  if (__baseNumber_isset) {
    if (__baseNumber != nil) {
      [outProtocol writeFieldBeginWithName: @"baseNumber" type: TType_STRING fieldID: 1];
      [outProtocol writeString: __baseNumber];
      [outProtocol writeFieldEnd];
    }
  }
  if (__primeNumber_isset) {
    if (__primeNumber != nil) {
      [outProtocol writeFieldBeginWithName: @"primeNumber" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __primeNumber];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"ThriftDHPublicNumbersResponse("];
  [ms appendString: @"baseNumber:"];
  [ms appendFormat: @"\"%@\"", __baseNumber];
  [ms appendString: @",primeNumber:"];
  [ms appendFormat: @"\"%@\"", __primeNumber];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

