//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsMessage.h>
#import <EsMessageType.h>
#import <EsRequest.h>
#import <EsResponse.h>
#import <EsEvent.h>
#import <EsEntity.h>
#import <EsObject.h>
#import <ThriftEncryptionStateChangeEvent.h>

/**
 * Event fired when the encryption state of a client changes.
 That is, when the client either enables or disables encryption,
 and the server then acknowledges this change.
 
 The client uses code such as
 <pre>
     _es.engine.setEncryptionEnabled(true);
 </pre>
 
 to enable or disable encryption.  The client should then refrain
 from sending any messages to the server until it hears the 
 EncryptionStateChangeEvent.
 */
@interface EsEncryptionStateChangeEvent : EsEvent {
@private
	BOOL encryptionOn_set_;
	BOOL encryptionOn_;
}

@property(nonatomic) BOOL encryptionOn;

- (id) init;
- (id) initWithThriftObject: (id) thriftObject;
- (void) fromThrift: (id) thriftObject;
- (ThriftEncryptionStateChangeEvent*) toThrift;
- (id) newThrift;
@end
