//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsMessage.h>
#import <EsMessageType.h>
#import <EsRequest.h>
#import <EsResponse.h>
#import <EsEvent.h>
#import <EsEntity.h>
#import <EsObject.h>
#import <ThriftFindZoneAndRoomByNameRequest.h>

/**
 * Knowing the name of a room and the name of a zone you can request the id of the room and the id of the zone. This request leads to FindZoneAndRoomByNameResponse.
 * 
 * This example shows how to request the id of a zone and room and capture the response.
 
 <pre>
private var _es:ElectroServer;

private function initialize():void {
        _es.engine.addEventListener(MessageType.FindZoneAndRoomByNameResponse.name, onFindZoneAndRoomByNameResponse);

        var fzar:FindZoneAndRoomByNameRequest = new FindZoneAndRoomByNameRequest();
        fzar.roomName = "MyRoom";
        fzar.zoneName = "MyZone";

        _es.engine.send(fzar);
}

private function onFindZoneAndRoomByNameResponse(e:FindZoneAndRoomByNameResponse):void {
        trace("zoneId: " + e.roomAndZoneList[0].toString());
        trace("roomId: " + e.roomAndZoneList[1].toString());
}

 </pre>
 */
@interface EsFindZoneAndRoomByNameRequest : EsRequest {
@private
	BOOL zoneName_set_;
	NSString* zoneName_;
	BOOL roomName_set_;
	NSString* roomName_;
}

/**
 * Name of the zone whose id you want.
 */
@property(retain,nonatomic) NSString* zoneName;
/**
 * Name of the room whose id you want.
 */
@property(retain,nonatomic) NSString* roomName;

- (id) init;
- (id) initWithThriftObject: (id) thriftObject;
- (void) fromThrift: (id) thriftObject;
- (ThriftFindZoneAndRoomByNameRequest*) toThrift;
- (id) newThrift;
@end
