//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsMessage.h>
#import <EsMessageType.h>
#import <EsRequest.h>
#import <EsResponse.h>
#import <EsEvent.h>
#import <EsEntity.h>
#import <EsObject.h>
#import <ThriftFlattenedEsObject.h>

@interface EsFlattenedEsObject : EsEntity {
@private
	BOOL encodedEntries_set_;
	NSMutableArray* encodedEntries_;
}

@property(retain,nonatomic) NSMutableArray* encodedEntries;

- (id) init;
- (id) initWithThriftObject: (id) thriftObject;
- (void) fromThrift: (id) thriftObject;
- (ThriftFlattenedEsObject*) toThrift;
- (id) newThrift;
@end
