//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsMessage.h>
#import <EsMessageType.h>
#import <EsRequest.h>
#import <EsResponse.h>
#import <EsEvent.h>
#import <EsEntity.h>
#import <EsObject.h>
#import <ThriftGetUsersInRoomResponse.h>
#import <EsFlattenedEsObject.h>
#import <ThriftFlattenedEsObject.h>
#import <EsUserListEntry.h>
#import <ThriftUserListEntry.h>
#import <EsUserVariable.h>
#import <ThriftUserVariable.h>

/**
 * This is the response to the GetUsersInRoomRequest. It contains a list of 
 UserListEntry objects describing the list of users. Each UserListEntry object contains properties about a user such as the userName and userVariables.
 * 
 * This example shows how to request the list of users in a room, capture the response, and print the results.
<pre>
private var _es:ElectroServer;
private var _room:Room;

private function initialize():void {
        _es.engine.addEventListener(MessageType.GetUsersInRoomResponse.name, onGetUsersInRoomResponse);

        var guir:GetUsersInRoomRequest = new GetUsersInRoomRequest();
        guir.zoneId = _room.zoneId;
        guir.roomId = _room.id;
        _es.engine.send(guir);
}

private function onGetUsersInRoomResponse(e:GetUsersInRoomResponse):void {
        trace("Users in this room: " + e.roomId.toString());
        for each (var ule:UserListEntry in e.users) {
                trace(ule.userName);
        }
}
</pre>
 */
@interface EsGetUsersInRoomResponse : EsResponse {
@private
	BOOL zoneId_set_;
	int32_t zoneId_;
	BOOL roomId_set_;
	int32_t roomId_;
	BOOL users_set_;
	NSMutableArray* users_;
}

/**
 * Id of the zone that contains the room.
 */
@property(nonatomic) int32_t zoneId;
/**
 * Id of the room that contains the users.
 */
@property(nonatomic) int32_t roomId;
/**
 * List of UserListEntry objects, each of which describe a user in the room.
 */
@property(retain,nonatomic) NSMutableArray* users;

- (id) init;
- (id) initWithThriftObject: (id) thriftObject;
- (void) fromThrift: (id) thriftObject;
- (ThriftGetUsersInRoomResponse*) toThrift;
- (id) newThrift;
@end
