//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsMessage.h>
#import <EsMessageType.h>
#import <EsRequest.h>
#import <EsResponse.h>
#import <EsEvent.h>
#import <EsEntity.h>
#import <EsObject.h>
#import <ThriftGetRoomsInZoneRequest.h>

/**
 * This request allows the client to ask for a list of all of the rooms in a specific zone. Either the zone name or the zone id needs to be specified. This request leads to a 
 GetRoomsInZoneResponse, which contains a list of RoomListEntry object, each describing a room in that zone.
 * 
 * This example shows how to request the rooms in a zone, listen for the response to that request, and print out the results.
<pre>
private var _es:ElectroServer;

private function initialize():void {
        _es.engine.addEventListener(MessageType.GetRoomsInZoneResponse.name, onGetRoomsInZoneResponse);

        var griz:GetRoomsInZoneRequest = new GetRoomsInZoneRequest();
        griz.zoneName = "GameZone";
        _es.engine.send(griz);
}

private function onGetRoomsInZoneResponse(e:GetRoomsInZoneResponse):void {
        trace("Zone: "+e.zoneName + ", " + e.zoneName.toString());
        for each (var rle:RoomListEntry in e.entries) {
                trace("Room: "+rle.roomName + ", " + rle.roomId.toString());
        }
}
</pre>
 */
@interface EsGetRoomsInZoneRequest : EsRequest {
@private
	BOOL zoneId_set_;
	int32_t zoneId_;
	BOOL zoneName_set_;
	NSString* zoneName_;
}

/**
 * Id of the zone whose rooms are to be loaded. Either this property or the zoneName property must be specified.
 */
@property(nonatomic) int32_t zoneId;
/**
 * Name of the zone whose rooms are to be loaded. Either this property or the zoneId property must be specified.
 */
@property(retain,nonatomic) NSString* zoneName;

- (id) init;
- (id) initWithThriftObject: (id) thriftObject;
- (void) fromThrift: (id) thriftObject;
- (ThriftGetRoomsInZoneRequest*) toThrift;
- (id) newThrift;
@end
