//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsMessage.h>
#import <EsMessageType.h>
#import <EsRequest.h>
#import <EsResponse.h>
#import <EsEvent.h>
#import <EsEntity.h>
#import <EsObject.h>
#import <ThriftIdleTimeoutWarningEvent.h>

/**
 * When a user is in danger of being kicked from the server due to idleness, 
 this event occurs. If the client immediately sends a message to the server 
 (any type of message at all), the user will not be kicked due to idleness.
 */
@interface EsIdleTimeoutWarningEvent : EsEvent {
@private
}


- (id) init;
- (id) initWithThriftObject: (id) thriftObject;
- (void) fromThrift: (id) thriftObject;
- (ThriftIdleTimeoutWarningEvent*) toThrift;
- (id) newThrift;
@end
