//
//  Autogenerated by CocoaTouchApiGenerator
//
//  DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//



#import <EsMessage.h>
#import <EsMessageType.h>
#import <EsRequest.h>
#import <EsResponse.h>
#import <EsEvent.h>
#import <EsEntity.h>
#import <EsObject.h>
#import <ThriftZoneListEntry.h>

@interface EsZoneListEntry : EsEntity {
@private
	BOOL zoneId_set_;
	int32_t zoneId_;
	BOOL zoneName_set_;
	NSString* zoneName_;
}

@property(nonatomic) int32_t zoneId;
@property(retain,nonatomic) NSString* zoneName;

- (id) init;
- (id) initWithThriftObject: (id) thriftObject;
- (void) fromThrift: (id) thriftObject;
- (ThriftZoneListEntry*) toThrift;
- (id) newThrift;
@end
