/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>


enum ThriftServerState {
  ThriftServerState_NOOP = 1,
  ThriftServerState_RUNNING = 2,
  ThriftServerState_PAUSED = 3,
  ThriftServerState_STOPPED = 4
};

@interface ThriftServerStateConstants : NSObject {
}
@end
