/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>

#import "ThriftFlattenedEsObject.h"
#import "ThriftUserVariable.h"
#import "ThriftUserUpdateAction.h"

@interface ThriftUserUpdateEvent : NSObject <NSCoding> {
  int32_t __zoneId;
  int32_t __roomId;
  int __action;
  NSString * __userName;
  NSArray * __userVariables;
  BOOL __sendingVideo;
  NSString * __videoStreamName;

  BOOL __zoneId_isset;
  BOOL __roomId_isset;
  BOOL __action_isset;
  BOOL __userName_isset;
  BOOL __userVariables_isset;
  BOOL __sendingVideo_isset;
  BOOL __videoStreamName_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=zoneId, setter=setZoneId:) int32_t zoneId;
@property (nonatomic, getter=roomId, setter=setRoomId:) int32_t roomId;
@property (nonatomic, getter=action, setter=setAction:) int action;
@property (nonatomic, retain, getter=userName, setter=setUserName:) NSString * userName;
@property (nonatomic, retain, getter=userVariables, setter=setUserVariables:) NSArray * userVariables;
@property (nonatomic, getter=sendingVideo, setter=setSendingVideo:) BOOL sendingVideo;
@property (nonatomic, retain, getter=videoStreamName, setter=setVideoStreamName:) NSString * videoStreamName;
#endif

- (id) initWithZoneId: (int32_t) zoneId roomId: (int32_t) roomId action: (int) action userName: (NSString *) userName userVariables: (NSArray *) userVariables sendingVideo: (BOOL) sendingVideo videoStreamName: (NSString *) videoStreamName;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (int32_t) zoneId;
- (void) setZoneId: (int32_t) zoneId;
- (BOOL) zoneIdIsSet;

- (int32_t) roomId;
- (void) setRoomId: (int32_t) roomId;
- (BOOL) roomIdIsSet;

- (int) action;
- (void) setAction: (int) action;
- (BOOL) actionIsSet;

- (NSString *) userName;
- (void) setUserName: (NSString *) userName;
- (BOOL) userNameIsSet;

- (NSArray *) userVariables;
- (void) setUserVariables: (NSArray *) userVariables;
- (BOOL) userVariablesIsSet;

- (BOOL) sendingVideo;
- (void) setSendingVideo: (BOOL) sendingVideo;
- (BOOL) sendingVideoIsSet;

- (NSString *) videoStreamName;
- (void) setVideoStreamName: (NSString *) videoStreamName;
- (BOOL) videoStreamNameIsSet;

@end

@interface ThriftUserUpdateEventConstants : NSObject {
}
@end
