/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>


@interface ThriftJoinRoomRequest : NSObject <NSCoding> {
  NSString * __zoneName;
  NSString * __roomName;
  int32_t __zoneId;
  int32_t __roomId;
  NSString * __password;
  BOOL __receivingRoomListUpdates;
  BOOL __receivingRoomAttributeUpdates;
  BOOL __receivingUserListUpdates;
  BOOL __receivingUserVariableUpdates;
  BOOL __receivingRoomVariableUpdates;
  BOOL __receivingVideoEvents;

  BOOL __zoneName_isset;
  BOOL __roomName_isset;
  BOOL __zoneId_isset;
  BOOL __roomId_isset;
  BOOL __password_isset;
  BOOL __receivingRoomListUpdates_isset;
  BOOL __receivingRoomAttributeUpdates_isset;
  BOOL __receivingUserListUpdates_isset;
  BOOL __receivingUserVariableUpdates_isset;
  BOOL __receivingRoomVariableUpdates_isset;
  BOOL __receivingVideoEvents_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=zoneName, setter=setZoneName:) NSString * zoneName;
@property (nonatomic, retain, getter=roomName, setter=setRoomName:) NSString * roomName;
@property (nonatomic, getter=zoneId, setter=setZoneId:) int32_t zoneId;
@property (nonatomic, getter=roomId, setter=setRoomId:) int32_t roomId;
@property (nonatomic, retain, getter=password, setter=setPassword:) NSString * password;
@property (nonatomic, getter=receivingRoomListUpdates, setter=setReceivingRoomListUpdates:) BOOL receivingRoomListUpdates;
@property (nonatomic, getter=receivingRoomAttributeUpdates, setter=setReceivingRoomAttributeUpdates:) BOOL receivingRoomAttributeUpdates;
@property (nonatomic, getter=receivingUserListUpdates, setter=setReceivingUserListUpdates:) BOOL receivingUserListUpdates;
@property (nonatomic, getter=receivingUserVariableUpdates, setter=setReceivingUserVariableUpdates:) BOOL receivingUserVariableUpdates;
@property (nonatomic, getter=receivingRoomVariableUpdates, setter=setReceivingRoomVariableUpdates:) BOOL receivingRoomVariableUpdates;
@property (nonatomic, getter=receivingVideoEvents, setter=setReceivingVideoEvents:) BOOL receivingVideoEvents;
#endif

- (id) initWithZoneName: (NSString *) zoneName roomName: (NSString *) roomName zoneId: (int32_t) zoneId roomId: (int32_t) roomId password: (NSString *) password receivingRoomListUpdates: (BOOL) receivingRoomListUpdates receivingRoomAttributeUpdates: (BOOL) receivingRoomAttributeUpdates receivingUserListUpdates: (BOOL) receivingUserListUpdates receivingUserVariableUpdates: (BOOL) receivingUserVariableUpdates receivingRoomVariableUpdates: (BOOL) receivingRoomVariableUpdates receivingVideoEvents: (BOOL) receivingVideoEvents;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) zoneName;
- (void) setZoneName: (NSString *) zoneName;
- (BOOL) zoneNameIsSet;

- (NSString *) roomName;
- (void) setRoomName: (NSString *) roomName;
- (BOOL) roomNameIsSet;

- (int32_t) zoneId;
- (void) setZoneId: (int32_t) zoneId;
- (BOOL) zoneIdIsSet;

- (int32_t) roomId;
- (void) setRoomId: (int32_t) roomId;
- (BOOL) roomIdIsSet;

- (NSString *) password;
- (void) setPassword: (NSString *) password;
- (BOOL) passwordIsSet;

- (BOOL) receivingRoomListUpdates;
- (void) setReceivingRoomListUpdates: (BOOL) receivingRoomListUpdates;
- (BOOL) receivingRoomListUpdatesIsSet;

- (BOOL) receivingRoomAttributeUpdates;
- (void) setReceivingRoomAttributeUpdates: (BOOL) receivingRoomAttributeUpdates;
- (BOOL) receivingRoomAttributeUpdatesIsSet;

- (BOOL) receivingUserListUpdates;
- (void) setReceivingUserListUpdates: (BOOL) receivingUserListUpdates;
- (BOOL) receivingUserListUpdatesIsSet;

- (BOOL) receivingUserVariableUpdates;
- (void) setReceivingUserVariableUpdates: (BOOL) receivingUserVariableUpdates;
- (BOOL) receivingUserVariableUpdatesIsSet;

- (BOOL) receivingRoomVariableUpdates;
- (void) setReceivingRoomVariableUpdates: (BOOL) receivingRoomVariableUpdates;
- (BOOL) receivingRoomVariableUpdatesIsSet;

- (BOOL) receivingVideoEvents;
- (void) setReceivingVideoEvents: (BOOL) receivingVideoEvents;
- (BOOL) receivingVideoEventsIsSet;

@end

@interface ThriftJoinRoomRequestConstants : NSObject {
}
@end
