/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>

#import "ThriftFlattenedEsObject.h"

@interface ThriftPluginMessageEvent : NSObject <NSCoding> {
  NSString * __pluginName;
  BOOL __sentToRoom;
  int32_t __destinationZoneId;
  int32_t __destinationRoomId;
  BOOL __roomLevelPlugin;
  int32_t __originZoneId;
  int32_t __originRoomId;
  ThriftFlattenedEsObject * __parameters;

  BOOL __pluginName_isset;
  BOOL __sentToRoom_isset;
  BOOL __destinationZoneId_isset;
  BOOL __destinationRoomId_isset;
  BOOL __roomLevelPlugin_isset;
  BOOL __originZoneId_isset;
  BOOL __originRoomId_isset;
  BOOL __parameters_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=pluginName, setter=setPluginName:) NSString * pluginName;
@property (nonatomic, getter=sentToRoom, setter=setSentToRoom:) BOOL sentToRoom;
@property (nonatomic, getter=destinationZoneId, setter=setDestinationZoneId:) int32_t destinationZoneId;
@property (nonatomic, getter=destinationRoomId, setter=setDestinationRoomId:) int32_t destinationRoomId;
@property (nonatomic, getter=roomLevelPlugin, setter=setRoomLevelPlugin:) BOOL roomLevelPlugin;
@property (nonatomic, getter=originZoneId, setter=setOriginZoneId:) int32_t originZoneId;
@property (nonatomic, getter=originRoomId, setter=setOriginRoomId:) int32_t originRoomId;
@property (nonatomic, retain, getter=parameters, setter=setParameters:) ThriftFlattenedEsObject * parameters;
#endif

- (id) initWithPluginName: (NSString *) pluginName sentToRoom: (BOOL) sentToRoom destinationZoneId: (int32_t) destinationZoneId destinationRoomId: (int32_t) destinationRoomId roomLevelPlugin: (BOOL) roomLevelPlugin originZoneId: (int32_t) originZoneId originRoomId: (int32_t) originRoomId parameters: (ThriftFlattenedEsObject *) parameters;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) pluginName;
- (void) setPluginName: (NSString *) pluginName;
- (BOOL) pluginNameIsSet;

- (BOOL) sentToRoom;
- (void) setSentToRoom: (BOOL) sentToRoom;
- (BOOL) sentToRoomIsSet;

- (int32_t) destinationZoneId;
- (void) setDestinationZoneId: (int32_t) destinationZoneId;
- (BOOL) destinationZoneIdIsSet;

- (int32_t) destinationRoomId;
- (void) setDestinationRoomId: (int32_t) destinationRoomId;
- (BOOL) destinationRoomIdIsSet;

- (BOOL) roomLevelPlugin;
- (void) setRoomLevelPlugin: (BOOL) roomLevelPlugin;
- (BOOL) roomLevelPluginIsSet;

- (int32_t) originZoneId;
- (void) setOriginZoneId: (int32_t) originZoneId;
- (BOOL) originZoneIdIsSet;

- (int32_t) originRoomId;
- (void) setOriginRoomId: (int32_t) originRoomId;
- (BOOL) originRoomIdIsSet;

- (ThriftFlattenedEsObject *) parameters;
- (void) setParameters: (ThriftFlattenedEsObject *) parameters;
- (BOOL) parametersIsSet;

@end

@interface ThriftPluginMessageEventConstants : NSObject {
}
@end
