/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>

#import "ThriftFlattenedEsObject.h"

@interface ThriftServerGame : NSObject <NSCoding> {
  ThriftFlattenedEsObject * __gameDetails;
  int32_t __id;
  int32_t __roomId;
  int32_t __zoneId;
  BOOL __locked;
  BOOL __passwordProtected;

  BOOL __gameDetails_isset;
  BOOL __id_isset;
  BOOL __roomId_isset;
  BOOL __zoneId_isset;
  BOOL __locked_isset;
  BOOL __passwordProtected_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=gameDetails, setter=setGameDetails:) ThriftFlattenedEsObject * gameDetails;
@property (nonatomic, getter=id, setter=setId:) int32_t id;
@property (nonatomic, getter=roomId, setter=setRoomId:) int32_t roomId;
@property (nonatomic, getter=zoneId, setter=setZoneId:) int32_t zoneId;
@property (nonatomic, getter=locked, setter=setLocked:) BOOL locked;
@property (nonatomic, getter=passwordProtected, setter=setPasswordProtected:) BOOL passwordProtected;
#endif

- (id) initWithGameDetails: (ThriftFlattenedEsObject *) gameDetails id: (int32_t) id roomId: (int32_t) roomId zoneId: (int32_t) zoneId locked: (BOOL) locked passwordProtected: (BOOL) passwordProtected;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (ThriftFlattenedEsObject *) gameDetails;
- (void) setGameDetails: (ThriftFlattenedEsObject *) gameDetails;
- (BOOL) gameDetailsIsSet;

- (int32_t) id;
- (void) setId: (int32_t) id;
- (BOOL) idIsSet;

- (int32_t) roomId;
- (void) setRoomId: (int32_t) roomId;
- (BOOL) roomIdIsSet;

- (int32_t) zoneId;
- (void) setZoneId: (int32_t) zoneId;
- (BOOL) zoneIdIsSet;

- (BOOL) locked;
- (void) setLocked: (BOOL) locked;
- (BOOL) lockedIsSet;

- (BOOL) passwordProtected;
- (void) setPasswordProtected: (BOOL) passwordProtected;
- (BOOL) passwordProtectedIsSet;

@end

@interface ThriftServerGameConstants : NSObject {
}
@end
