/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>


enum ThriftZoneUpdateAction {
  ThriftZoneUpdateAction_AddRoom = 1,
  ThriftZoneUpdateAction_DeleteRoom = 2,
  ThriftZoneUpdateAction_UpdateRoom = 3
};

@interface ThriftZoneUpdateActionConstants : NSObject {
}
@end
