/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>

#import "ThriftFlattenedEsObject.h"
#import "ThriftRequestDetails.h"

@interface ThriftAggregatePluginRequest : NSObject <NSCoding> {
  NSArray * __pluginRequestArray;

  BOOL __pluginRequestArray_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=pluginRequestArray, setter=setPluginRequestArray:) NSArray * pluginRequestArray;
#endif

- (id) initWithPluginRequestArray: (NSArray *) pluginRequestArray;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSArray *) pluginRequestArray;
- (void) setPluginRequestArray: (NSArray *) pluginRequestArray;
- (BOOL) pluginRequestArrayIsSet;

@end

@interface ThriftAggregatePluginRequestConstants : NSObject {
}
@end
