/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>


enum ThriftRoomVariableUpdateAction {
  ThriftRoomVariableUpdateAction_VariableCreated = 1,
  ThriftRoomVariableUpdateAction_VariableUpdated = 2,
  ThriftRoomVariableUpdateAction_VariableDeleted = 3
};

@interface ThriftRoomVariableUpdateActionConstants : NSObject {
}
@end
