/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>


@interface ThriftGatewayStatistics : NSObject <NSCoding> {
  int64_t __bytesInTotal;
  int64_t __bytesOutTotal;
  int64_t __messagesInTotal;
  int64_t __messagesOutTotal;

  BOOL __bytesInTotal_isset;
  BOOL __bytesOutTotal_isset;
  BOOL __messagesInTotal_isset;
  BOOL __messagesOutTotal_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=bytesInTotal, setter=setBytesInTotal:) int64_t bytesInTotal;
@property (nonatomic, getter=bytesOutTotal, setter=setBytesOutTotal:) int64_t bytesOutTotal;
@property (nonatomic, getter=messagesInTotal, setter=setMessagesInTotal:) int64_t messagesInTotal;
@property (nonatomic, getter=messagesOutTotal, setter=setMessagesOutTotal:) int64_t messagesOutTotal;
#endif

- (id) initWithBytesInTotal: (int64_t) bytesInTotal bytesOutTotal: (int64_t) bytesOutTotal messagesInTotal: (int64_t) messagesInTotal messagesOutTotal: (int64_t) messagesOutTotal;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (int64_t) bytesInTotal;
- (void) setBytesInTotal: (int64_t) bytesInTotal;
- (BOOL) bytesInTotalIsSet;

- (int64_t) bytesOutTotal;
- (void) setBytesOutTotal: (int64_t) bytesOutTotal;
- (BOOL) bytesOutTotalIsSet;

- (int64_t) messagesInTotal;
- (void) setMessagesInTotal: (int64_t) messagesInTotal;
- (BOOL) messagesInTotalIsSet;

- (int64_t) messagesOutTotal;
- (void) setMessagesOutTotal: (int64_t) messagesOutTotal;
- (BOOL) messagesOutTotalIsSet;

@end

@interface ThriftGatewayStatisticsConstants : NSObject {
}
@end
