/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>

#import "ThriftFlattenedEsObject.h"
#import "ThriftPluginListEntry.h"
#import "ThriftRoomVariable.h"

@interface ThriftCreateRoomRequest : NSObject <NSCoding> {
  NSString * __zoneName;
  int32_t __zoneId;
  NSString * __roomName;
  int32_t __capacity;
  NSString * __password;
  NSString * __roomDescription;
  BOOL __persistent;
  BOOL __hidden;
  BOOL __receivingRoomListUpdates;
  BOOL __receivingRoomAttributeUpdates;
  BOOL __receivingUserListUpdates;
  BOOL __receivingUserVariableUpdates;
  BOOL __receivingRoomVariableUpdates;
  BOOL __receivingVideoEvents;
  BOOL __nonOperatorUpdateAllowed;
  BOOL __nonOperatorVariableUpdateAllowed;
  BOOL __createOrJoinRoom;
  NSArray * __plugins;
  NSArray * __variables;
  BOOL __usingLanguageFilter;
  BOOL __languageFilterSpecified;
  NSString * __languageFilterName;
  BOOL __languageFilterDeliverMessageOnFailure;
  int32_t __languageFilterFailuresBeforeKick;
  int32_t __languageFilterKicksBeforeBan;
  int32_t __languageFilterBanDuration;
  BOOL __languageFilterResetAfterKick;
  BOOL __usingFloodingFilter;
  BOOL __floodingFilterSpecified;
  NSString * __floodingFilterName;
  int32_t __floodingFilterFailuresBeforeKick;
  int32_t __floodingFilterKicksBeforeBan;
  int32_t __floodingFilterBanDuration;
  BOOL __floodingFilterResetAfterKick;

  BOOL __zoneName_isset;
  BOOL __zoneId_isset;
  BOOL __roomName_isset;
  BOOL __capacity_isset;
  BOOL __password_isset;
  BOOL __roomDescription_isset;
  BOOL __persistent_isset;
  BOOL __hidden_isset;
  BOOL __receivingRoomListUpdates_isset;
  BOOL __receivingRoomAttributeUpdates_isset;
  BOOL __receivingUserListUpdates_isset;
  BOOL __receivingUserVariableUpdates_isset;
  BOOL __receivingRoomVariableUpdates_isset;
  BOOL __receivingVideoEvents_isset;
  BOOL __nonOperatorUpdateAllowed_isset;
  BOOL __nonOperatorVariableUpdateAllowed_isset;
  BOOL __createOrJoinRoom_isset;
  BOOL __plugins_isset;
  BOOL __variables_isset;
  BOOL __usingLanguageFilter_isset;
  BOOL __languageFilterSpecified_isset;
  BOOL __languageFilterName_isset;
  BOOL __languageFilterDeliverMessageOnFailure_isset;
  BOOL __languageFilterFailuresBeforeKick_isset;
  BOOL __languageFilterKicksBeforeBan_isset;
  BOOL __languageFilterBanDuration_isset;
  BOOL __languageFilterResetAfterKick_isset;
  BOOL __usingFloodingFilter_isset;
  BOOL __floodingFilterSpecified_isset;
  BOOL __floodingFilterName_isset;
  BOOL __floodingFilterFailuresBeforeKick_isset;
  BOOL __floodingFilterKicksBeforeBan_isset;
  BOOL __floodingFilterBanDuration_isset;
  BOOL __floodingFilterResetAfterKick_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=zoneName, setter=setZoneName:) NSString * zoneName;
@property (nonatomic, getter=zoneId, setter=setZoneId:) int32_t zoneId;
@property (nonatomic, retain, getter=roomName, setter=setRoomName:) NSString * roomName;
@property (nonatomic, getter=capacity, setter=setCapacity:) int32_t capacity;
@property (nonatomic, retain, getter=password, setter=setPassword:) NSString * password;
@property (nonatomic, retain, getter=roomDescription, setter=setRoomDescription:) NSString * roomDescription;
@property (nonatomic, getter=persistent, setter=setPersistent:) BOOL persistent;
@property (nonatomic, getter=hidden, setter=setHidden:) BOOL hidden;
@property (nonatomic, getter=receivingRoomListUpdates, setter=setReceivingRoomListUpdates:) BOOL receivingRoomListUpdates;
@property (nonatomic, getter=receivingRoomAttributeUpdates, setter=setReceivingRoomAttributeUpdates:) BOOL receivingRoomAttributeUpdates;
@property (nonatomic, getter=receivingUserListUpdates, setter=setReceivingUserListUpdates:) BOOL receivingUserListUpdates;
@property (nonatomic, getter=receivingUserVariableUpdates, setter=setReceivingUserVariableUpdates:) BOOL receivingUserVariableUpdates;
@property (nonatomic, getter=receivingRoomVariableUpdates, setter=setReceivingRoomVariableUpdates:) BOOL receivingRoomVariableUpdates;
@property (nonatomic, getter=receivingVideoEvents, setter=setReceivingVideoEvents:) BOOL receivingVideoEvents;
@property (nonatomic, getter=nonOperatorUpdateAllowed, setter=setNonOperatorUpdateAllowed:) BOOL nonOperatorUpdateAllowed;
@property (nonatomic, getter=nonOperatorVariableUpdateAllowed, setter=setNonOperatorVariableUpdateAllowed:) BOOL nonOperatorVariableUpdateAllowed;
@property (nonatomic, getter=createOrJoinRoom, setter=setCreateOrJoinRoom:) BOOL createOrJoinRoom;
@property (nonatomic, retain, getter=plugins, setter=setPlugins:) NSArray * plugins;
@property (nonatomic, retain, getter=variables, setter=setVariables:) NSArray * variables;
@property (nonatomic, getter=usingLanguageFilter, setter=setUsingLanguageFilter:) BOOL usingLanguageFilter;
@property (nonatomic, getter=languageFilterSpecified, setter=setLanguageFilterSpecified:) BOOL languageFilterSpecified;
@property (nonatomic, retain, getter=languageFilterName, setter=setLanguageFilterName:) NSString * languageFilterName;
@property (nonatomic, getter=languageFilterDeliverMessageOnFailure, setter=setLanguageFilterDeliverMessageOnFailure:) BOOL languageFilterDeliverMessageOnFailure;
@property (nonatomic, getter=languageFilterFailuresBeforeKick, setter=setLanguageFilterFailuresBeforeKick:) int32_t languageFilterFailuresBeforeKick;
@property (nonatomic, getter=languageFilterKicksBeforeBan, setter=setLanguageFilterKicksBeforeBan:) int32_t languageFilterKicksBeforeBan;
@property (nonatomic, getter=languageFilterBanDuration, setter=setLanguageFilterBanDuration:) int32_t languageFilterBanDuration;
@property (nonatomic, getter=languageFilterResetAfterKick, setter=setLanguageFilterResetAfterKick:) BOOL languageFilterResetAfterKick;
@property (nonatomic, getter=usingFloodingFilter, setter=setUsingFloodingFilter:) BOOL usingFloodingFilter;
@property (nonatomic, getter=floodingFilterSpecified, setter=setFloodingFilterSpecified:) BOOL floodingFilterSpecified;
@property (nonatomic, retain, getter=floodingFilterName, setter=setFloodingFilterName:) NSString * floodingFilterName;
@property (nonatomic, getter=floodingFilterFailuresBeforeKick, setter=setFloodingFilterFailuresBeforeKick:) int32_t floodingFilterFailuresBeforeKick;
@property (nonatomic, getter=floodingFilterKicksBeforeBan, setter=setFloodingFilterKicksBeforeBan:) int32_t floodingFilterKicksBeforeBan;
@property (nonatomic, getter=floodingFilterBanDuration, setter=setFloodingFilterBanDuration:) int32_t floodingFilterBanDuration;
@property (nonatomic, getter=floodingFilterResetAfterKick, setter=setFloodingFilterResetAfterKick:) BOOL floodingFilterResetAfterKick;
#endif

- (id) initWithZoneName: (NSString *) zoneName zoneId: (int32_t) zoneId roomName: (NSString *) roomName capacity: (int32_t) capacity password: (NSString *) password roomDescription: (NSString *) roomDescription persistent: (BOOL) persistent hidden: (BOOL) hidden receivingRoomListUpdates: (BOOL) receivingRoomListUpdates receivingRoomAttributeUpdates: (BOOL) receivingRoomAttributeUpdates receivingUserListUpdates: (BOOL) receivingUserListUpdates receivingUserVariableUpdates: (BOOL) receivingUserVariableUpdates receivingRoomVariableUpdates: (BOOL) receivingRoomVariableUpdates receivingVideoEvents: (BOOL) receivingVideoEvents nonOperatorUpdateAllowed: (BOOL) nonOperatorUpdateAllowed nonOperatorVariableUpdateAllowed: (BOOL) nonOperatorVariableUpdateAllowed createOrJoinRoom: (BOOL) createOrJoinRoom plugins: (NSArray *) plugins variables: (NSArray *) variables usingLanguageFilter: (BOOL) usingLanguageFilter languageFilterSpecified: (BOOL) languageFilterSpecified languageFilterName: (NSString *) languageFilterName languageFilterDeliverMessageOnFailure: (BOOL) languageFilterDeliverMessageOnFailure languageFilterFailuresBeforeKick: (int32_t) languageFilterFailuresBeforeKick languageFilterKicksBeforeBan: (int32_t) languageFilterKicksBeforeBan languageFilterBanDuration: (int32_t) languageFilterBanDuration languageFilterResetAfterKick: (BOOL) languageFilterResetAfterKick usingFloodingFilter: (BOOL) usingFloodingFilter floodingFilterSpecified: (BOOL) floodingFilterSpecified floodingFilterName: (NSString *) floodingFilterName floodingFilterFailuresBeforeKick: (int32_t) floodingFilterFailuresBeforeKick floodingFilterKicksBeforeBan: (int32_t) floodingFilterKicksBeforeBan floodingFilterBanDuration: (int32_t) floodingFilterBanDuration floodingFilterResetAfterKick: (BOOL) floodingFilterResetAfterKick;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) zoneName;
- (void) setZoneName: (NSString *) zoneName;
- (BOOL) zoneNameIsSet;

- (int32_t) zoneId;
- (void) setZoneId: (int32_t) zoneId;
- (BOOL) zoneIdIsSet;

- (NSString *) roomName;
- (void) setRoomName: (NSString *) roomName;
- (BOOL) roomNameIsSet;

- (int32_t) capacity;
- (void) setCapacity: (int32_t) capacity;
- (BOOL) capacityIsSet;

- (NSString *) password;
- (void) setPassword: (NSString *) password;
- (BOOL) passwordIsSet;

- (NSString *) roomDescription;
- (void) setRoomDescription: (NSString *) roomDescription;
- (BOOL) roomDescriptionIsSet;

- (BOOL) persistent;
- (void) setPersistent: (BOOL) persistent;
- (BOOL) persistentIsSet;

- (BOOL) hidden;
- (void) setHidden: (BOOL) hidden;
- (BOOL) hiddenIsSet;

- (BOOL) receivingRoomListUpdates;
- (void) setReceivingRoomListUpdates: (BOOL) receivingRoomListUpdates;
- (BOOL) receivingRoomListUpdatesIsSet;

- (BOOL) receivingRoomAttributeUpdates;
- (void) setReceivingRoomAttributeUpdates: (BOOL) receivingRoomAttributeUpdates;
- (BOOL) receivingRoomAttributeUpdatesIsSet;

- (BOOL) receivingUserListUpdates;
- (void) setReceivingUserListUpdates: (BOOL) receivingUserListUpdates;
- (BOOL) receivingUserListUpdatesIsSet;

- (BOOL) receivingUserVariableUpdates;
- (void) setReceivingUserVariableUpdates: (BOOL) receivingUserVariableUpdates;
- (BOOL) receivingUserVariableUpdatesIsSet;

- (BOOL) receivingRoomVariableUpdates;
- (void) setReceivingRoomVariableUpdates: (BOOL) receivingRoomVariableUpdates;
- (BOOL) receivingRoomVariableUpdatesIsSet;

- (BOOL) receivingVideoEvents;
- (void) setReceivingVideoEvents: (BOOL) receivingVideoEvents;
- (BOOL) receivingVideoEventsIsSet;

- (BOOL) nonOperatorUpdateAllowed;
- (void) setNonOperatorUpdateAllowed: (BOOL) nonOperatorUpdateAllowed;
- (BOOL) nonOperatorUpdateAllowedIsSet;

- (BOOL) nonOperatorVariableUpdateAllowed;
- (void) setNonOperatorVariableUpdateAllowed: (BOOL) nonOperatorVariableUpdateAllowed;
- (BOOL) nonOperatorVariableUpdateAllowedIsSet;

- (BOOL) createOrJoinRoom;
- (void) setCreateOrJoinRoom: (BOOL) createOrJoinRoom;
- (BOOL) createOrJoinRoomIsSet;

- (NSArray *) plugins;
- (void) setPlugins: (NSArray *) plugins;
- (BOOL) pluginsIsSet;

- (NSArray *) variables;
- (void) setVariables: (NSArray *) variables;
- (BOOL) variablesIsSet;

- (BOOL) usingLanguageFilter;
- (void) setUsingLanguageFilter: (BOOL) usingLanguageFilter;
- (BOOL) usingLanguageFilterIsSet;

- (BOOL) languageFilterSpecified;
- (void) setLanguageFilterSpecified: (BOOL) languageFilterSpecified;
- (BOOL) languageFilterSpecifiedIsSet;

- (NSString *) languageFilterName;
- (void) setLanguageFilterName: (NSString *) languageFilterName;
- (BOOL) languageFilterNameIsSet;

- (BOOL) languageFilterDeliverMessageOnFailure;
- (void) setLanguageFilterDeliverMessageOnFailure: (BOOL) languageFilterDeliverMessageOnFailure;
- (BOOL) languageFilterDeliverMessageOnFailureIsSet;

- (int32_t) languageFilterFailuresBeforeKick;
- (void) setLanguageFilterFailuresBeforeKick: (int32_t) languageFilterFailuresBeforeKick;
- (BOOL) languageFilterFailuresBeforeKickIsSet;

- (int32_t) languageFilterKicksBeforeBan;
- (void) setLanguageFilterKicksBeforeBan: (int32_t) languageFilterKicksBeforeBan;
- (BOOL) languageFilterKicksBeforeBanIsSet;

- (int32_t) languageFilterBanDuration;
- (void) setLanguageFilterBanDuration: (int32_t) languageFilterBanDuration;
- (BOOL) languageFilterBanDurationIsSet;

- (BOOL) languageFilterResetAfterKick;
- (void) setLanguageFilterResetAfterKick: (BOOL) languageFilterResetAfterKick;
- (BOOL) languageFilterResetAfterKickIsSet;

- (BOOL) usingFloodingFilter;
- (void) setUsingFloodingFilter: (BOOL) usingFloodingFilter;
- (BOOL) usingFloodingFilterIsSet;

- (BOOL) floodingFilterSpecified;
- (void) setFloodingFilterSpecified: (BOOL) floodingFilterSpecified;
- (BOOL) floodingFilterSpecifiedIsSet;

- (NSString *) floodingFilterName;
- (void) setFloodingFilterName: (NSString *) floodingFilterName;
- (BOOL) floodingFilterNameIsSet;

- (int32_t) floodingFilterFailuresBeforeKick;
- (void) setFloodingFilterFailuresBeforeKick: (int32_t) floodingFilterFailuresBeforeKick;
- (BOOL) floodingFilterFailuresBeforeKickIsSet;

- (int32_t) floodingFilterKicksBeforeBan;
- (void) setFloodingFilterKicksBeforeBan: (int32_t) floodingFilterKicksBeforeBan;
- (BOOL) floodingFilterKicksBeforeBanIsSet;

- (int32_t) floodingFilterBanDuration;
- (void) setFloodingFilterBanDuration: (int32_t) floodingFilterBanDuration;
- (BOOL) floodingFilterBanDurationIsSet;

- (BOOL) floodingFilterResetAfterKick;
- (void) setFloodingFilterResetAfterKick: (BOOL) floodingFilterResetAfterKick;
- (BOOL) floodingFilterResetAfterKickIsSet;

@end

@interface ThriftCreateRoomRequestConstants : NSObject {
}
@end
