/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>


@interface ThriftProtocolConfiguration : NSObject <NSCoding> {
  int32_t __messageCompressionThreshold;

  BOOL __messageCompressionThreshold_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=messageCompressionThreshold, setter=setMessageCompressionThreshold:) int32_t messageCompressionThreshold;
#endif

- (id) initWithMessageCompressionThreshold: (int32_t) messageCompressionThreshold;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (int32_t) messageCompressionThreshold;
- (void) setMessageCompressionThreshold: (int32_t) messageCompressionThreshold;
- (BOOL) messageCompressionThresholdIsSet;

@end

@interface ThriftProtocolConfigurationConstants : NSObject {
}
@end
