/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>

#import "ThriftErrorType.h"

@interface ThriftRegisterUDPConnectionResponse : NSObject <NSCoding> {
  BOOL __successful;
  int32_t __sessionKey;
  int __error;

  BOOL __successful_isset;
  BOOL __sessionKey_isset;
  BOOL __error_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=successful, setter=setSuccessful:) BOOL successful;
@property (nonatomic, getter=sessionKey, setter=setSessionKey:) int32_t sessionKey;
@property (nonatomic, getter=error, setter=setError:) int error;
#endif

- (id) initWithSuccessful: (BOOL) successful sessionKey: (int32_t) sessionKey error: (int) error;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (BOOL) successful;
- (void) setSuccessful: (BOOL) successful;
- (BOOL) successfulIsSet;

- (int32_t) sessionKey;
- (void) setSessionKey: (int32_t) sessionKey;
- (BOOL) sessionKeyIsSet;

- (int) error;
- (void) setError: (int) error;
- (BOOL) errorIsSet;

@end

@interface ThriftRegisterUDPConnectionResponseConstants : NSObject {
}
@end
