/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>

#import "ThriftRoomListEntry.h"

@interface ThriftGetRoomsInZoneResponse : NSObject <NSCoding> {
  int32_t __zoneId;
  NSString * __zoneName;
  NSArray * __entries;

  BOOL __zoneId_isset;
  BOOL __zoneName_isset;
  BOOL __entries_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=zoneId, setter=setZoneId:) int32_t zoneId;
@property (nonatomic, retain, getter=zoneName, setter=setZoneName:) NSString * zoneName;
@property (nonatomic, retain, getter=entries, setter=setEntries:) NSArray * entries;
#endif

- (id) initWithZoneId: (int32_t) zoneId zoneName: (NSString *) zoneName entries: (NSArray *) entries;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (int32_t) zoneId;
- (void) setZoneId: (int32_t) zoneId;
- (BOOL) zoneIdIsSet;

- (NSString *) zoneName;
- (void) setZoneName: (NSString *) zoneName;
- (BOOL) zoneNameIsSet;

- (NSArray *) entries;
- (void) setEntries: (NSArray *) entries;
- (BOOL) entriesIsSet;

@end

@interface ThriftGetRoomsInZoneResponseConstants : NSObject {
}
@end
