/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>


@interface ThriftGetServerLocalTimeResponse : NSObject <NSCoding> {
  int64_t __serverLocalTimeInMilliseconds;

  BOOL __serverLocalTimeInMilliseconds_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=serverLocalTimeInMilliseconds, setter=setServerLocalTimeInMilliseconds:) int64_t serverLocalTimeInMilliseconds;
#endif

- (id) initWithServerLocalTimeInMilliseconds: (int64_t) serverLocalTimeInMilliseconds;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (int64_t) serverLocalTimeInMilliseconds;
- (void) setServerLocalTimeInMilliseconds: (int64_t) serverLocalTimeInMilliseconds;
- (BOOL) serverLocalTimeInMillisecondsIsSet;

@end

@interface ThriftGetServerLocalTimeResponseConstants : NSObject {
}
@end
