/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>


@interface ThriftLogOutRequest : NSObject <NSCoding> {
  BOOL __dropConnection;
  BOOL __dropAllConnections;

  BOOL __dropConnection_isset;
  BOOL __dropAllConnections_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=dropConnection, setter=setDropConnection:) BOOL dropConnection;
@property (nonatomic, getter=dropAllConnections, setter=setDropAllConnections:) BOOL dropAllConnections;
#endif

- (id) initWithDropConnection: (BOOL) dropConnection dropAllConnections: (BOOL) dropAllConnections;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (BOOL) dropConnection;
- (void) setDropConnection: (BOOL) dropConnection;
- (BOOL) dropConnectionIsSet;

- (BOOL) dropAllConnections;
- (void) setDropAllConnections: (BOOL) dropAllConnections;
- (BOOL) dropAllConnectionsIsSet;

@end

@interface ThriftLogOutRequestConstants : NSObject {
}
@end
