/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>

#import "ThriftFlattenedEsObject.h"

@interface ThriftUpdateRoomVariableRequest : NSObject <NSCoding> {
  int32_t __zoneId;
  int32_t __roomId;
  NSString * __name;
  BOOL __valueChanged;
  ThriftFlattenedEsObject * __value;
  BOOL __lockStatusChanged;
  BOOL __locked;

  BOOL __zoneId_isset;
  BOOL __roomId_isset;
  BOOL __name_isset;
  BOOL __valueChanged_isset;
  BOOL __value_isset;
  BOOL __lockStatusChanged_isset;
  BOOL __locked_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=zoneId, setter=setZoneId:) int32_t zoneId;
@property (nonatomic, getter=roomId, setter=setRoomId:) int32_t roomId;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, getter=valueChanged, setter=setValueChanged:) BOOL valueChanged;
@property (nonatomic, retain, getter=value, setter=setValue:) ThriftFlattenedEsObject * value;
@property (nonatomic, getter=lockStatusChanged, setter=setLockStatusChanged:) BOOL lockStatusChanged;
@property (nonatomic, getter=locked, setter=setLocked:) BOOL locked;
#endif

- (id) initWithZoneId: (int32_t) zoneId roomId: (int32_t) roomId name: (NSString *) name valueChanged: (BOOL) valueChanged value: (ThriftFlattenedEsObject *) value lockStatusChanged: (BOOL) lockStatusChanged locked: (BOOL) locked;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (int32_t) zoneId;
- (void) setZoneId: (int32_t) zoneId;
- (BOOL) zoneIdIsSet;

- (int32_t) roomId;
- (void) setRoomId: (int32_t) roomId;
- (BOOL) roomIdIsSet;

- (NSString *) name;
- (void) setName: (NSString *) name;
- (BOOL) nameIsSet;

- (BOOL) valueChanged;
- (void) setValueChanged: (BOOL) valueChanged;
- (BOOL) valueChangedIsSet;

- (ThriftFlattenedEsObject *) value;
- (void) setValue: (ThriftFlattenedEsObject *) value;
- (BOOL) valueIsSet;

- (BOOL) lockStatusChanged;
- (void) setLockStatusChanged: (BOOL) lockStatusChanged;
- (BOOL) lockStatusChangedIsSet;

- (BOOL) locked;
- (void) setLocked: (BOOL) locked;
- (BOOL) lockedIsSet;

@end

@interface ThriftUpdateRoomVariableRequestConstants : NSObject {
}
@end
