/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>

#import "ThriftFlattenedEsObject.h"
#import "ThriftFlattenedEsObjectRO.h"
#import "ThriftProtocol.h"

@interface ThriftLoginRequest : NSObject <NSCoding> {
  NSString * __userName;
  NSString * __password;
  NSString * __sharedSecret;
  ThriftFlattenedEsObjectRO * __esObject;
  NSDictionary * __userVariables;
  int __protocol;
  int32_t __hashId;
  NSString * __clientVersion;
  NSString * __clientType;
  NSArray * __remoteAddress;

  BOOL __userName_isset;
  BOOL __password_isset;
  BOOL __sharedSecret_isset;
  BOOL __esObject_isset;
  BOOL __userVariables_isset;
  BOOL __protocol_isset;
  BOOL __hashId_isset;
  BOOL __clientVersion_isset;
  BOOL __clientType_isset;
  BOOL __remoteAddress_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=userName, setter=setUserName:) NSString * userName;
@property (nonatomic, retain, getter=password, setter=setPassword:) NSString * password;
@property (nonatomic, retain, getter=sharedSecret, setter=setSharedSecret:) NSString * sharedSecret;
@property (nonatomic, retain, getter=esObject, setter=setEsObject:) ThriftFlattenedEsObjectRO * esObject;
@property (nonatomic, retain, getter=userVariables, setter=setUserVariables:) NSDictionary * userVariables;
@property (nonatomic, getter=protocol, setter=setProtocol:) int protocol;
@property (nonatomic, getter=hashId, setter=setHashId:) int32_t hashId;
@property (nonatomic, retain, getter=clientVersion, setter=setClientVersion:) NSString * clientVersion;
@property (nonatomic, retain, getter=clientType, setter=setClientType:) NSString * clientType;
@property (nonatomic, retain, getter=remoteAddress, setter=setRemoteAddress:) NSArray * remoteAddress;
#endif

- (id) initWithUserName: (NSString *) userName password: (NSString *) password sharedSecret: (NSString *) sharedSecret esObject: (ThriftFlattenedEsObjectRO *) esObject userVariables: (NSDictionary *) userVariables protocol: (int) protocol hashId: (int32_t) hashId clientVersion: (NSString *) clientVersion clientType: (NSString *) clientType remoteAddress: (NSArray *) remoteAddress;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) userName;
- (void) setUserName: (NSString *) userName;
- (BOOL) userNameIsSet;

- (NSString *) password;
- (void) setPassword: (NSString *) password;
- (BOOL) passwordIsSet;

- (NSString *) sharedSecret;
- (void) setSharedSecret: (NSString *) sharedSecret;
- (BOOL) sharedSecretIsSet;

- (ThriftFlattenedEsObjectRO *) esObject;
- (void) setEsObject: (ThriftFlattenedEsObjectRO *) esObject;
- (BOOL) esObjectIsSet;

- (NSDictionary *) userVariables;
- (void) setUserVariables: (NSDictionary *) userVariables;
- (BOOL) userVariablesIsSet;

- (int) protocol;
- (void) setProtocol: (int) protocol;
- (BOOL) protocolIsSet;

- (int32_t) hashId;
- (void) setHashId: (int32_t) hashId;
- (BOOL) hashIdIsSet;

- (NSString *) clientVersion;
- (void) setClientVersion: (NSString *) clientVersion;
- (BOOL) clientVersionIsSet;

- (NSString *) clientType;
- (void) setClientType: (NSString *) clientType;
- (BOOL) clientTypeIsSet;

- (NSArray *) remoteAddress;
- (void) setRemoteAddress: (NSArray *) remoteAddress;
- (BOOL) remoteAddressIsSet;

@end

@interface ThriftLoginRequestConstants : NSObject {
}
@end
