/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>

#import "ThriftFlattenedEsObject.h"

@interface ThriftPublicMessageEvent : NSObject <NSCoding> {
  NSString * __message;
  NSString * __userName;
  int32_t __zoneId;
  int32_t __roomId;
  ThriftFlattenedEsObject * __esObject;

  BOOL __message_isset;
  BOOL __userName_isset;
  BOOL __zoneId_isset;
  BOOL __roomId_isset;
  BOOL __esObject_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
@property (nonatomic, retain, getter=userName, setter=setUserName:) NSString * userName;
@property (nonatomic, getter=zoneId, setter=setZoneId:) int32_t zoneId;
@property (nonatomic, getter=roomId, setter=setRoomId:) int32_t roomId;
@property (nonatomic, retain, getter=esObject, setter=setEsObject:) ThriftFlattenedEsObject * esObject;
#endif

- (id) initWithMessage: (NSString *) message userName: (NSString *) userName zoneId: (int32_t) zoneId roomId: (int32_t) roomId esObject: (ThriftFlattenedEsObject *) esObject;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) message;
- (void) setMessage: (NSString *) message;
- (BOOL) messageIsSet;

- (NSString *) userName;
- (void) setUserName: (NSString *) userName;
- (BOOL) userNameIsSet;

- (int32_t) zoneId;
- (void) setZoneId: (int32_t) zoneId;
- (BOOL) zoneIdIsSet;

- (int32_t) roomId;
- (void) setRoomId: (int32_t) roomId;
- (BOOL) roomIdIsSet;

- (ThriftFlattenedEsObject *) esObject;
- (void) setEsObject: (ThriftFlattenedEsObject *) esObject;
- (BOOL) esObjectIsSet;

@end

@interface ThriftPublicMessageEventConstants : NSObject {
}
@end
