/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>

#import "ThriftFlattenedEsObject.h"
#import "ThriftRoomVariable.h"
#import "ThriftUserListEntry.h"
#import "ThriftUserVariable.h"

@interface ThriftJoinRoomEvent : NSObject <NSCoding> {
  int32_t __zoneId;
  int32_t __roomId;
  NSString * __roomName;
  NSString * __roomDescription;
  BOOL __hasPassword;
  BOOL __hidden;
  int32_t __capacity;
  NSArray * __users;
  NSArray * __roomVariables;

  BOOL __zoneId_isset;
  BOOL __roomId_isset;
  BOOL __roomName_isset;
  BOOL __roomDescription_isset;
  BOOL __hasPassword_isset;
  BOOL __hidden_isset;
  BOOL __capacity_isset;
  BOOL __users_isset;
  BOOL __roomVariables_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=zoneId, setter=setZoneId:) int32_t zoneId;
@property (nonatomic, getter=roomId, setter=setRoomId:) int32_t roomId;
@property (nonatomic, retain, getter=roomName, setter=setRoomName:) NSString * roomName;
@property (nonatomic, retain, getter=roomDescription, setter=setRoomDescription:) NSString * roomDescription;
@property (nonatomic, getter=hasPassword, setter=setHasPassword:) BOOL hasPassword;
@property (nonatomic, getter=hidden, setter=setHidden:) BOOL hidden;
@property (nonatomic, getter=capacity, setter=setCapacity:) int32_t capacity;
@property (nonatomic, retain, getter=users, setter=setUsers:) NSArray * users;
@property (nonatomic, retain, getter=roomVariables, setter=setRoomVariables:) NSArray * roomVariables;
#endif

- (id) initWithZoneId: (int32_t) zoneId roomId: (int32_t) roomId roomName: (NSString *) roomName roomDescription: (NSString *) roomDescription hasPassword: (BOOL) hasPassword hidden: (BOOL) hidden capacity: (int32_t) capacity users: (NSArray *) users roomVariables: (NSArray *) roomVariables;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (int32_t) zoneId;
- (void) setZoneId: (int32_t) zoneId;
- (BOOL) zoneIdIsSet;

- (int32_t) roomId;
- (void) setRoomId: (int32_t) roomId;
- (BOOL) roomIdIsSet;

- (NSString *) roomName;
- (void) setRoomName: (NSString *) roomName;
- (BOOL) roomNameIsSet;

- (NSString *) roomDescription;
- (void) setRoomDescription: (NSString *) roomDescription;
- (BOOL) roomDescriptionIsSet;

- (BOOL) hasPassword;
- (void) setHasPassword: (BOOL) hasPassword;
- (BOOL) hasPasswordIsSet;

- (BOOL) hidden;
- (void) setHidden: (BOOL) hidden;
- (BOOL) hiddenIsSet;

- (int32_t) capacity;
- (void) setCapacity: (int32_t) capacity;
- (BOOL) capacityIsSet;

- (NSArray *) users;
- (void) setUsers: (NSArray *) users;
- (BOOL) usersIsSet;

- (NSArray *) roomVariables;
- (void) setRoomVariables: (NSArray *) roomVariables;
- (BOOL) roomVariablesIsSet;

@end

@interface ThriftJoinRoomEventConstants : NSObject {
}
@end
