/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>

#import "ThriftFlattenedEsObjectRO.h"
#import "ThriftErrorType.h"

@interface ThriftLoginResponse : NSObject <NSCoding> {
  BOOL __successful;
  int __error;
  ThriftFlattenedEsObjectRO * __esObject;
  NSString * __userName;
  NSDictionary * __userVariables;
  NSDictionary * __buddyListEntries;

  BOOL __successful_isset;
  BOOL __error_isset;
  BOOL __esObject_isset;
  BOOL __userName_isset;
  BOOL __userVariables_isset;
  BOOL __buddyListEntries_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=successful, setter=setSuccessful:) BOOL successful;
@property (nonatomic, getter=error, setter=setError:) int error;
@property (nonatomic, retain, getter=esObject, setter=setEsObject:) ThriftFlattenedEsObjectRO * esObject;
@property (nonatomic, retain, getter=userName, setter=setUserName:) NSString * userName;
@property (nonatomic, retain, getter=userVariables, setter=setUserVariables:) NSDictionary * userVariables;
@property (nonatomic, retain, getter=buddyListEntries, setter=setBuddyListEntries:) NSDictionary * buddyListEntries;
#endif

- (id) initWithSuccessful: (BOOL) successful error: (int) error esObject: (ThriftFlattenedEsObjectRO *) esObject userName: (NSString *) userName userVariables: (NSDictionary *) userVariables buddyListEntries: (NSDictionary *) buddyListEntries;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (BOOL) successful;
- (void) setSuccessful: (BOOL) successful;
- (BOOL) successfulIsSet;

- (int) error;
- (void) setError: (int) error;
- (BOOL) errorIsSet;

- (ThriftFlattenedEsObjectRO *) esObject;
- (void) setEsObject: (ThriftFlattenedEsObjectRO *) esObject;
- (BOOL) esObjectIsSet;

- (NSString *) userName;
- (void) setUserName: (NSString *) userName;
- (BOOL) userNameIsSet;

- (NSDictionary *) userVariables;
- (void) setUserVariables: (NSDictionary *) userVariables;
- (BOOL) userVariablesIsSet;

- (NSDictionary *) buddyListEntries;
- (void) setBuddyListEntries: (NSDictionary *) buddyListEntries;
- (BOOL) buddyListEntriesIsSet;

@end

@interface ThriftLoginResponseConstants : NSObject {
}
@end
