/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>


@interface ThriftFlattenedEsObjectRO : NSObject <NSCoding> {
  NSArray * __encodedEntries;

  BOOL __encodedEntries_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=encodedEntries, setter=setEncodedEntries:) NSArray * encodedEntries;
#endif

- (id) initWithEncodedEntries: (NSArray *) encodedEntries;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSArray *) encodedEntries;
- (void) setEncodedEntries: (NSArray *) encodedEntries;
- (BOOL) encodedEntriesIsSet;

@end

@interface ThriftFlattenedEsObjectROConstants : NSObject {
}
@end
